// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rest_response.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Details              []string `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_343c0b34fe72ecf7, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetDetails() []string {
	if m != nil {
		return m.Details
	}
	return nil
}

type Response struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// repeated Error errors = 2;
	Errors               map[string]*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_343c0b34fe72ecf7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetErrors() map[string]*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "rest.Error")
	proto.RegisterType((*Response)(nil), "rest.Response")
	proto.RegisterMapType((map[string]*Error)(nil), "rest.Response.ErrorsEntry")
}

func init() { proto.RegisterFile("rest_response.proto", fileDescriptor_343c0b34fe72ecf7) }

var fileDescriptor_343c0b34fe72ecf7 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x6e, 0xf3, 0x20,
	0x18, 0x85, 0x85, 0x9d, 0xe4, 0x4b, 0xf0, 0x37, 0x54, 0x74, 0xb1, 0x32, 0x39, 0x99, 0x58, 0x82,
	0x55, 0x67, 0xa9, 0x3a, 0x56, 0x4a, 0x2f, 0x80, 0xb1, 0x4b, 0x45, 0xcc, 0xab, 0x1a, 0xf9, 0x87,
	0x88, 0x17, 0x22, 0xe5, 0xbe, 0x7a, 0x81, 0x15, 0x24, 0x96, 0xba, 0x9d, 0x03, 0xcf, 0xe1, 0x91,
	0xa0, 0xcf, 0x0e, 0xd0, 0x7f, 0x39, 0xc0, 0x8b, 0x9d, 0x10, 0xc4, 0xc5, 0x59, 0x6f, 0xd9, 0x22,
	0x1e, 0xee, 0x77, 0x74, 0x79, 0x72, 0xce, 0x3a, 0x56, 0xd2, 0x7f, 0x1a, 0xbc, 0x32, 0x03, 0x96,
	0xa4, 0xca, 0xf9, 0x46, 0xce, 0x75, 0xff, 0x43, 0xe8, 0x5a, 0x3e, 0xb6, 0x11, 0xc3, 0xd0, 0xb6,
	0x80, 0x11, 0x23, 0x7c, 0x2d, 0xe7, 0xca, 0x1a, 0xba, 0x82, 0xf8, 0x12, 0x96, 0x59, 0x95, 0xf3,
	0xa2, 0xd9, 0x8a, 0x28, 0x10, 0xf3, 0x52, 0x24, 0x0d, 0x9e, 0x26, 0xef, 0x6e, 0xf2, 0x41, 0x32,
	0x46, 0x17, 0x5a, 0x79, 0x55, 0xe6, 0x15, 0xe1, 0xff, 0x65, 0xca, 0xdb, 0x0f, 0x5a, 0xfc, 0x41,
	0xd9, 0x13, 0xcd, 0x7b, 0xb8, 0x25, 0xd9, 0x46, 0xc6, 0xc8, 0x76, 0x74, 0x79, 0x55, 0x43, 0x80,
	0x32, 0xab, 0x08, 0x2f, 0x9a, 0xe2, 0xee, 0x49, 0x1b, 0x79, 0xbf, 0x79, 0xcb, 0x5e, 0xc9, 0xfb,
	0xf1, 0xf3, 0xe5, 0xdb, 0xf8, 0x2e, 0x9c, 0x45, 0x6b, 0xc7, 0xda, 0x0c, 0x9d, 0x1a, 0xc7, 0x4e,
	0xeb, 0xba, 0x0f, 0x5a, 0xf5, 0xe6, 0x10, 0x10, 0xdc, 0x01, 0xc1, 0x5d, 0x4d, 0x0b, 0x35, 0x4c,
	0xde, 0x78, 0x03, 0x78, 0x5e, 0xa5, 0xbf, 0x39, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x8b,
	0x21, 0x6b, 0x32, 0x01, 0x00, 0x00,
}
