// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/kudaki_event.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	kudaki_event "github.com/ilhammhdd/kudaki-user-service/entities/domains/kudaki_event"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProposeEventAd struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventAd              *kudaki_event.EventAd `protobuf:"bytes,2,opt,name=event_ad,json=eventAd,proto3" json:"event_ad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProposeEventAd) Reset()         { *m = ProposeEventAd{} }
func (m *ProposeEventAd) String() string { return proto.CompactTextString(m) }
func (*ProposeEventAd) ProtoMessage()    {}
func (*ProposeEventAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6addef9ba51ecee, []int{0}
}

func (m *ProposeEventAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeEventAd.Unmarshal(m, b)
}
func (m *ProposeEventAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeEventAd.Marshal(b, m, deterministic)
}
func (m *ProposeEventAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeEventAd.Merge(m, src)
}
func (m *ProposeEventAd) XXX_Size() int {
	return xxx_messageInfo_ProposeEventAd.Size(m)
}
func (m *ProposeEventAd) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeEventAd.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeEventAd proto.InternalMessageInfo

func (m *ProposeEventAd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProposeEventAd) GetEventAd() *kudaki_event.EventAd {
	if m != nil {
		return m.EventAd
	}
	return nil
}

type VerifyOrganizerAndEvent struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventAd              *kudaki_event.EventAd `protobuf:"bytes,2,opt,name=event_ad,json=eventAd,proto3" json:"event_ad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VerifyOrganizerAndEvent) Reset()         { *m = VerifyOrganizerAndEvent{} }
func (m *VerifyOrganizerAndEvent) String() string { return proto.CompactTextString(m) }
func (*VerifyOrganizerAndEvent) ProtoMessage()    {}
func (*VerifyOrganizerAndEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6addef9ba51ecee, []int{1}
}

func (m *VerifyOrganizerAndEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOrganizerAndEvent.Unmarshal(m, b)
}
func (m *VerifyOrganizerAndEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOrganizerAndEvent.Marshal(b, m, deterministic)
}
func (m *VerifyOrganizerAndEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOrganizerAndEvent.Merge(m, src)
}
func (m *VerifyOrganizerAndEvent) XXX_Size() int {
	return xxx_messageInfo_VerifyOrganizerAndEvent.Size(m)
}
func (m *VerifyOrganizerAndEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOrganizerAndEvent.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOrganizerAndEvent proto.InternalMessageInfo

func (m *VerifyOrganizerAndEvent) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *VerifyOrganizerAndEvent) GetEventAd() *kudaki_event.EventAd {
	if m != nil {
		return m.EventAd
	}
	return nil
}

type PublishEventAd struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventAd              *kudaki_event.EventAd `protobuf:"bytes,2,opt,name=event_ad,json=eventAd,proto3" json:"event_ad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PublishEventAd) Reset()         { *m = PublishEventAd{} }
func (m *PublishEventAd) String() string { return proto.CompactTextString(m) }
func (*PublishEventAd) ProtoMessage()    {}
func (*PublishEventAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6addef9ba51ecee, []int{2}
}

func (m *PublishEventAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishEventAd.Unmarshal(m, b)
}
func (m *PublishEventAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishEventAd.Marshal(b, m, deterministic)
}
func (m *PublishEventAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishEventAd.Merge(m, src)
}
func (m *PublishEventAd) XXX_Size() int {
	return xxx_messageInfo_PublishEventAd.Size(m)
}
func (m *PublishEventAd) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishEventAd.DiscardUnknown(m)
}

var xxx_messageInfo_PublishEventAd proto.InternalMessageInfo

func (m *PublishEventAd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PublishEventAd) GetEventAd() *kudaki_event.EventAd {
	if m != nil {
		return m.EventAd
	}
	return nil
}

type RegisterToEvent struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventAd              *kudaki_event.EventAd `protobuf:"bytes,2,opt,name=event_ad,json=eventAd,proto3" json:"event_ad,omitempty"`
	User                 *user.User            `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisterToEvent) Reset()         { *m = RegisterToEvent{} }
func (m *RegisterToEvent) String() string { return proto.CompactTextString(m) }
func (*RegisterToEvent) ProtoMessage()    {}
func (*RegisterToEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6addef9ba51ecee, []int{3}
}

func (m *RegisterToEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterToEvent.Unmarshal(m, b)
}
func (m *RegisterToEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterToEvent.Marshal(b, m, deterministic)
}
func (m *RegisterToEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterToEvent.Merge(m, src)
}
func (m *RegisterToEvent) XXX_Size() int {
	return xxx_messageInfo_RegisterToEvent.Size(m)
}
func (m *RegisterToEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterToEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterToEvent proto.InternalMessageInfo

func (m *RegisterToEvent) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterToEvent) GetEventAd() *kudaki_event.EventAd {
	if m != nil {
		return m.EventAd
	}
	return nil
}

func (m *RegisterToEvent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*ProposeEventAd)(nil), "command.ProposeEventAd")
	proto.RegisterType((*VerifyOrganizerAndEvent)(nil), "command.VerifyOrganizerAndEvent")
	proto.RegisterType((*PublishEventAd)(nil), "command.PublishEventAd")
	proto.RegisterType((*RegisterToEvent)(nil), "command.RegisterToEvent")
}

func init() { proto.RegisterFile("commands/kudaki_event.proto", fileDescriptor_a6addef9ba51ecee) }

var fileDescriptor_a6addef9ba51ecee = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x2d, 0x56, 0x23, 0x28, 0xe6, 0xd2, 0x52, 0x3d, 0x94, 0x8a, 0xd0, 0x4b, 0x37,
	0xa0, 0x07, 0x41, 0xbc, 0x54, 0xf0, 0xac, 0x2c, 0xea, 0x41, 0x90, 0x92, 0xdd, 0x4c, 0x77, 0x87,
	0x36, 0x49, 0x99, 0x24, 0x05, 0xbd, 0xfb, 0xbf, 0x65, 0xb3, 0xbb, 0x87, 0xde, 0xeb, 0x65, 0x18,
	0x98, 0xef, 0xbd, 0xcc, 0xf0, 0xc2, 0x2e, 0x0b, 0xab, 0xb5, 0x34, 0xca, 0x89, 0x55, 0x50, 0x72,
	0x85, 0x0b, 0xd8, 0x82, 0xf1, 0xe9, 0x86, 0xac, 0xb7, 0xbc, 0xdf, 0x0e, 0x47, 0xd7, 0xca, 0x6a,
	0x89, 0x66, 0x17, 0x12, 0xb1, 0x2e, 0xa4, 0x6a, 0xe8, 0xd1, 0xa0, 0x83, 0x82, 0x03, 0x8a, 0xa5,
	0x19, 0x4c, 0xbe, 0xd8, 0xd9, 0x2b, 0xd9, 0x8d, 0x75, 0xf0, 0x5c, 0x2b, 0xe6, 0x8a, 0x73, 0xd6,
	0x0b, 0x01, 0xd5, 0x30, 0x19, 0x27, 0xd3, 0x93, 0x2c, 0xf6, 0xfc, 0x9e, 0x1d, 0x77, 0x86, 0xc3,
	0x83, 0x71, 0x32, 0x3d, 0xbd, 0xbd, 0x4a, 0x1b, 0xc7, 0x74, 0x67, 0xb5, 0xd6, 0x23, 0xeb, 0x43,
	0xd3, 0x4c, 0x96, 0x6c, 0xf0, 0x01, 0x84, 0xcb, 0xef, 0x17, 0x2a, 0xa5, 0xc1, 0x1f, 0xa0, 0xb9,
	0x51, 0x91, 0xda, 0xef, 0x3b, 0xf5, 0x19, 0x21, 0x5f, 0xa3, 0xab, 0xfe, 0xe5, 0x8c, 0xdf, 0x84,
	0x9d, 0x67, 0x50, 0xa2, 0xf3, 0x40, 0x6f, 0x76, 0xff, 0xfb, 0xf3, 0x1b, 0xd6, 0xab, 0x43, 0x19,
	0x1e, 0x46, 0xd1, 0x45, 0x27, 0x8a, 0x41, 0xbd, 0x3b, 0xa0, 0x2c, 0x8e, 0x9f, 0x1e, 0x3f, 0x1f,
	0x4a, 0xf4, 0x55, 0xc8, 0xd3, 0xc2, 0x6a, 0x81, 0xeb, 0x4a, 0x6a, 0x5d, 0x29, 0xd5, 0x46, 0x3f,
	0xab, 0x99, 0x99, 0x03, 0xda, 0x62, 0x01, 0x02, 0x8c, 0x47, 0x8f, 0xe0, 0x44, 0xf7, 0x8b, 0xf2,
	0xa3, 0x18, 0xf9, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x31, 0x1b, 0xcc, 0x58, 0x02,
	0x00, 0x00,
}
