// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/mountain.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	mountain "github.com/ilhammhdd/kudaki-user-service/entities/domains/mountain"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMountain struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mountain             *mountain.Mountain `protobuf:"bytes,2,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddMountain) Reset()         { *m = AddMountain{} }
func (m *AddMountain) String() string { return proto.CompactTextString(m) }
func (*AddMountain) ProtoMessage()    {}
func (*AddMountain) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{0}
}

func (m *AddMountain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMountain.Unmarshal(m, b)
}
func (m *AddMountain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMountain.Marshal(b, m, deterministic)
}
func (m *AddMountain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMountain.Merge(m, src)
}
func (m *AddMountain) XXX_Size() int {
	return xxx_messageInfo_AddMountain.Size(m)
}
func (m *AddMountain) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMountain.DiscardUnknown(m)
}

var xxx_messageInfo_AddMountain proto.InternalMessageInfo

func (m *AddMountain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddMountain) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type EditMountain struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mountain             *mountain.Mountain `protobuf:"bytes,2,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EditMountain) Reset()         { *m = EditMountain{} }
func (m *EditMountain) String() string { return proto.CompactTextString(m) }
func (*EditMountain) ProtoMessage()    {}
func (*EditMountain) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{1}
}

func (m *EditMountain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMountain.Unmarshal(m, b)
}
func (m *EditMountain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMountain.Marshal(b, m, deterministic)
}
func (m *EditMountain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMountain.Merge(m, src)
}
func (m *EditMountain) XXX_Size() int {
	return xxx_messageInfo_EditMountain.Size(m)
}
func (m *EditMountain) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMountain.DiscardUnknown(m)
}

var xxx_messageInfo_EditMountain proto.InternalMessageInfo

func (m *EditMountain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EditMountain) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type ReviewMountain struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Review               *mountain.Review `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReviewMountain) Reset()         { *m = ReviewMountain{} }
func (m *ReviewMountain) String() string { return proto.CompactTextString(m) }
func (*ReviewMountain) ProtoMessage()    {}
func (*ReviewMountain) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{2}
}

func (m *ReviewMountain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewMountain.Unmarshal(m, b)
}
func (m *ReviewMountain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewMountain.Marshal(b, m, deterministic)
}
func (m *ReviewMountain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewMountain.Merge(m, src)
}
func (m *ReviewMountain) XXX_Size() int {
	return xxx_messageInfo_ReviewMountain.Size(m)
}
func (m *ReviewMountain) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewMountain.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewMountain proto.InternalMessageInfo

func (m *ReviewMountain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReviewMountain) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type EditMountainReview struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Review               *mountain.Review `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EditMountainReview) Reset()         { *m = EditMountainReview{} }
func (m *EditMountainReview) String() string { return proto.CompactTextString(m) }
func (*EditMountainReview) ProtoMessage()    {}
func (*EditMountainReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{3}
}

func (m *EditMountainReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMountainReview.Unmarshal(m, b)
}
func (m *EditMountainReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMountainReview.Marshal(b, m, deterministic)
}
func (m *EditMountainReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMountainReview.Merge(m, src)
}
func (m *EditMountainReview) XXX_Size() int {
	return xxx_messageInfo_EditMountainReview.Size(m)
}
func (m *EditMountainReview) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMountainReview.DiscardUnknown(m)
}

var xxx_messageInfo_EditMountainReview proto.InternalMessageInfo

func (m *EditMountainReview) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EditMountainReview) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type DeleteMountainReview struct {
	Uuid                 string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Review               *mountain.Review `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteMountainReview) Reset()         { *m = DeleteMountainReview{} }
func (m *DeleteMountainReview) String() string { return proto.CompactTextString(m) }
func (*DeleteMountainReview) ProtoMessage()    {}
func (*DeleteMountainReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{4}
}

func (m *DeleteMountainReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMountainReview.Unmarshal(m, b)
}
func (m *DeleteMountainReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMountainReview.Marshal(b, m, deterministic)
}
func (m *DeleteMountainReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMountainReview.Merge(m, src)
}
func (m *DeleteMountainReview) XXX_Size() int {
	return xxx_messageInfo_DeleteMountainReview.Size(m)
}
func (m *DeleteMountainReview) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMountainReview.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMountainReview proto.InternalMessageInfo

func (m *DeleteMountainReview) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteMountainReview) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type AddRecomendedGear struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,2,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AddRecomendedGear) Reset()         { *m = AddRecomendedGear{} }
func (m *AddRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*AddRecomendedGear) ProtoMessage()    {}
func (*AddRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{5}
}

func (m *AddRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecomendedGear.Unmarshal(m, b)
}
func (m *AddRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecomendedGear.Marshal(b, m, deterministic)
}
func (m *AddRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecomendedGear.Merge(m, src)
}
func (m *AddRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_AddRecomendedGear.Size(m)
}
func (m *AddRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecomendedGear proto.InternalMessageInfo

func (m *AddRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddRecomendedGear) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type EditRecomendedGear struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,2,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *EditRecomendedGear) Reset()         { *m = EditRecomendedGear{} }
func (m *EditRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*EditRecomendedGear) ProtoMessage()    {}
func (*EditRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{6}
}

func (m *EditRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRecomendedGear.Unmarshal(m, b)
}
func (m *EditRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRecomendedGear.Marshal(b, m, deterministic)
}
func (m *EditRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRecomendedGear.Merge(m, src)
}
func (m *EditRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_EditRecomendedGear.Size(m)
}
func (m *EditRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_EditRecomendedGear proto.InternalMessageInfo

func (m *EditRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EditRecomendedGear) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type DeleteRecomendedGear struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,2,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeleteRecomendedGear) Reset()         { *m = DeleteRecomendedGear{} }
func (m *DeleteRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*DeleteRecomendedGear) ProtoMessage()    {}
func (*DeleteRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{7}
}

func (m *DeleteRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecomendedGear.Unmarshal(m, b)
}
func (m *DeleteRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecomendedGear.Marshal(b, m, deterministic)
}
func (m *DeleteRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecomendedGear.Merge(m, src)
}
func (m *DeleteRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_DeleteRecomendedGear.Size(m)
}
func (m *DeleteRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecomendedGear proto.InternalMessageInfo

func (m *DeleteRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteRecomendedGear) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type UpVoteRecomendedGear struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,2,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpVoteRecomendedGear) Reset()         { *m = UpVoteRecomendedGear{} }
func (m *UpVoteRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*UpVoteRecomendedGear) ProtoMessage()    {}
func (*UpVoteRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{8}
}

func (m *UpVoteRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpVoteRecomendedGear.Unmarshal(m, b)
}
func (m *UpVoteRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpVoteRecomendedGear.Marshal(b, m, deterministic)
}
func (m *UpVoteRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpVoteRecomendedGear.Merge(m, src)
}
func (m *UpVoteRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_UpVoteRecomendedGear.Size(m)
}
func (m *UpVoteRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_UpVoteRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_UpVoteRecomendedGear proto.InternalMessageInfo

func (m *UpVoteRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpVoteRecomendedGear) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type DownVoteRecomendedGear struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,2,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DownVoteRecomendedGear) Reset()         { *m = DownVoteRecomendedGear{} }
func (m *DownVoteRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*DownVoteRecomendedGear) ProtoMessage()    {}
func (*DownVoteRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{9}
}

func (m *DownVoteRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownVoteRecomendedGear.Unmarshal(m, b)
}
func (m *DownVoteRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownVoteRecomendedGear.Marshal(b, m, deterministic)
}
func (m *DownVoteRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownVoteRecomendedGear.Merge(m, src)
}
func (m *DownVoteRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_DownVoteRecomendedGear.Size(m)
}
func (m *DownVoteRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_DownVoteRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_DownVoteRecomendedGear proto.InternalMessageInfo

func (m *DownVoteRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DownVoteRecomendedGear) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type PlanTrip struct {
	Uuid                 string         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Trip                 *mountain.Trip `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlanTrip) Reset()         { *m = PlanTrip{} }
func (m *PlanTrip) String() string { return proto.CompactTextString(m) }
func (*PlanTrip) ProtoMessage()    {}
func (*PlanTrip) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{10}
}

func (m *PlanTrip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanTrip.Unmarshal(m, b)
}
func (m *PlanTrip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanTrip.Marshal(b, m, deterministic)
}
func (m *PlanTrip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanTrip.Merge(m, src)
}
func (m *PlanTrip) XXX_Size() int {
	return xxx_messageInfo_PlanTrip.Size(m)
}
func (m *PlanTrip) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanTrip.DiscardUnknown(m)
}

var xxx_messageInfo_PlanTrip proto.InternalMessageInfo

func (m *PlanTrip) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PlanTrip) GetTrip() *mountain.Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

type CancelTrip struct {
	Uuid                 string         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Trip                 *mountain.Trip `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CancelTrip) Reset()         { *m = CancelTrip{} }
func (m *CancelTrip) String() string { return proto.CompactTextString(m) }
func (*CancelTrip) ProtoMessage()    {}
func (*CancelTrip) Descriptor() ([]byte, []int) {
	return fileDescriptor_78720127cd41be97, []int{11}
}

func (m *CancelTrip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTrip.Unmarshal(m, b)
}
func (m *CancelTrip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTrip.Marshal(b, m, deterministic)
}
func (m *CancelTrip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTrip.Merge(m, src)
}
func (m *CancelTrip) XXX_Size() int {
	return xxx_messageInfo_CancelTrip.Size(m)
}
func (m *CancelTrip) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTrip.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTrip proto.InternalMessageInfo

func (m *CancelTrip) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CancelTrip) GetTrip() *mountain.Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

func init() {
	proto.RegisterType((*AddMountain)(nil), "command.AddMountain")
	proto.RegisterType((*EditMountain)(nil), "command.EditMountain")
	proto.RegisterType((*ReviewMountain)(nil), "command.ReviewMountain")
	proto.RegisterType((*EditMountainReview)(nil), "command.EditMountainReview")
	proto.RegisterType((*DeleteMountainReview)(nil), "command.DeleteMountainReview")
	proto.RegisterType((*AddRecomendedGear)(nil), "command.AddRecomendedGear")
	proto.RegisterType((*EditRecomendedGear)(nil), "command.EditRecomendedGear")
	proto.RegisterType((*DeleteRecomendedGear)(nil), "command.DeleteRecomendedGear")
	proto.RegisterType((*UpVoteRecomendedGear)(nil), "command.UpVoteRecomendedGear")
	proto.RegisterType((*DownVoteRecomendedGear)(nil), "command.DownVoteRecomendedGear")
	proto.RegisterType((*PlanTrip)(nil), "command.PlanTrip")
	proto.RegisterType((*CancelTrip)(nil), "command.CancelTrip")
}

func init() { proto.RegisterFile("commands/mountain.proto", fileDescriptor_78720127cd41be97) }

var fileDescriptor_78720127cd41be97 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xe9, 0x47, 0xe9, 0x57, 0xa7, 0x52, 0x31, 0xa8, 0xad, 0x15, 0x69, 0xc9, 0x41, 0xea,
	0xa1, 0x09, 0x28, 0x5e, 0xc4, 0x4b, 0xb5, 0xa2, 0x22, 0x82, 0x04, 0x2b, 0x56, 0x0f, 0xb2, 0xcd,
	0x2e, 0xed, 0xd2, 0xec, 0x6e, 0xdc, 0x6c, 0xda, 0x7f, 0x5f, 0x9a, 0x6c, 0x6a, 0x6d, 0x82, 0xa7,
	0x36, 0xb7, 0x84, 0xf7, 0xe6, 0xf7, 0x66, 0x87, 0x61, 0xa0, 0xe6, 0x0a, 0xc6, 0x10, 0xc7, 0x81,
	0xcd, 0x44, 0xc8, 0x15, 0xa2, 0xdc, 0xf2, 0xa5, 0x50, 0xc2, 0xf8, 0xaf, 0x85, 0x46, 0x13, 0x0b,
	0x86, 0x28, 0xff, 0x31, 0xac, 0x38, 0x1b, 0x27, 0x29, 0x83, 0x24, 0xae, 0x60, 0x84, 0x63, 0x82,
	0x3f, 0x47, 0x04, 0x49, 0xed, 0x3b, 0xce, 0xf0, 0x4d, 0x29, 0x99, 0x69, 0xf9, 0x28, 0x25, 0x2b,
	0x49, 0xfd, 0x58, 0x34, 0xdf, 0xa0, 0xd2, 0xc5, 0xf8, 0x49, 0x2b, 0x86, 0x01, 0xc5, 0x30, 0xa4,
	0xb8, 0x5e, 0x68, 0x15, 0xda, 0x5b, 0x4e, 0xf4, 0x6d, 0x5c, 0x40, 0x39, 0xa9, 0xac, 0xff, 0x6b,
	0x15, 0xda, 0x95, 0xb3, 0x43, 0x2b, 0x46, 0x5a, 0x8b, 0x86, 0x13, 0x80, 0xb3, 0xb0, 0x9a, 0x03,
	0xd8, 0xbe, 0xc5, 0x54, 0x6d, 0x02, 0xdd, 0x87, 0xaa, 0x13, 0xbd, 0xf0, 0x4f, 0xb8, 0x0d, 0xa5,
	0x78, 0x0e, 0x1a, 0x5d, 0x4b, 0xa1, 0x63, 0x88, 0xa3, 0x6d, 0xe6, 0x00, 0x8c, 0xe5, 0x8e, 0x63,
	0x75, 0x3d, 0xe8, 0x0f, 0xd8, 0xeb, 0x11, 0x8f, 0x28, 0xb2, 0x09, 0xf8, 0x17, 0xec, 0x76, 0x31,
	0x76, 0x16, 0xbb, 0x71, 0x47, 0x90, 0xcc, 0x24, 0xdf, 0xc3, 0xce, 0xca, 0x06, 0xe9, 0x88, 0x66,
	0x46, 0xc4, 0x32, 0xcd, 0xa9, 0xca, 0x5f, 0xff, 0xa6, 0x8c, 0x47, 0x95, 0x6b, 0xa6, 0x4a, 0x66,
	0x98, 0x77, 0x6a, 0xdf, 0x7f, 0x15, 0x39, 0xa7, 0x4e, 0xe1, 0xa0, 0x27, 0x66, 0x3c, 0xf7, 0xdc,
	0x07, 0x28, 0x3f, 0x7b, 0x88, 0xbf, 0x48, 0xea, 0x67, 0x26, 0x9d, 0x42, 0x71, 0x7e, 0x3c, 0x34,
	0x7e, 0x3f, 0x85, 0x9f, 0x17, 0x3a, 0x91, 0xc5, 0x7c, 0x04, 0xb8, 0x41, 0xdc, 0x25, 0xde, 0x1a,
	0x60, 0xd7, 0x57, 0xef, 0x97, 0x23, 0xaa, 0xc6, 0xe1, 0xd0, 0x72, 0x05, 0xb3, 0xa9, 0x37, 0x46,
	0x8c, 0x8d, 0x31, 0xb6, 0x27, 0x21, 0x46, 0x13, 0xda, 0x09, 0x03, 0x22, 0x3b, 0x01, 0x91, 0x53,
	0xea, 0x12, 0x9b, 0x70, 0x45, 0x15, 0x25, 0x81, 0x9d, 0x5c, 0xe0, 0x61, 0x29, 0xba, 0x75, 0xe7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xbc, 0x72, 0x28, 0x94, 0x05, 0x00, 0x00,
}
