// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/rental.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	rental "github.com/ilhammhdd/kudaki-user-service/entities/domains/rental"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddItemToStorefront struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Item                 *rental.Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddItemToStorefront) Reset()         { *m = AddItemToStorefront{} }
func (m *AddItemToStorefront) String() string { return proto.CompactTextString(m) }
func (*AddItemToStorefront) ProtoMessage()    {}
func (*AddItemToStorefront) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{0}
}

func (m *AddItemToStorefront) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemToStorefront.Unmarshal(m, b)
}
func (m *AddItemToStorefront) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemToStorefront.Marshal(b, m, deterministic)
}
func (m *AddItemToStorefront) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemToStorefront.Merge(m, src)
}
func (m *AddItemToStorefront) XXX_Size() int {
	return xxx_messageInfo_AddItemToStorefront.Size(m)
}
func (m *AddItemToStorefront) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemToStorefront.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemToStorefront proto.InternalMessageInfo

func (m *AddItemToStorefront) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddItemToStorefront) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type EditStorefrontItem struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OldItem              *rental.Item `protobuf:"bytes,2,opt,name=old_item,json=oldItem,proto3" json:"old_item,omitempty"`
	NewItem              *rental.Item `protobuf:"bytes,3,opt,name=new_item,json=newItem,proto3" json:"new_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditStorefrontItem) Reset()         { *m = EditStorefrontItem{} }
func (m *EditStorefrontItem) String() string { return proto.CompactTextString(m) }
func (*EditStorefrontItem) ProtoMessage()    {}
func (*EditStorefrontItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{1}
}

func (m *EditStorefrontItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditStorefrontItem.Unmarshal(m, b)
}
func (m *EditStorefrontItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditStorefrontItem.Marshal(b, m, deterministic)
}
func (m *EditStorefrontItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditStorefrontItem.Merge(m, src)
}
func (m *EditStorefrontItem) XXX_Size() int {
	return xxx_messageInfo_EditStorefrontItem.Size(m)
}
func (m *EditStorefrontItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EditStorefrontItem.DiscardUnknown(m)
}

var xxx_messageInfo_EditStorefrontItem proto.InternalMessageInfo

func (m *EditStorefrontItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EditStorefrontItem) GetOldItem() *rental.Item {
	if m != nil {
		return m.OldItem
	}
	return nil
}

func (m *EditStorefrontItem) GetNewItem() *rental.Item {
	if m != nil {
		return m.NewItem
	}
	return nil
}

type DeleteStorefrontItem struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Item                 *rental.Item `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteStorefrontItem) Reset()         { *m = DeleteStorefrontItem{} }
func (m *DeleteStorefrontItem) String() string { return proto.CompactTextString(m) }
func (*DeleteStorefrontItem) ProtoMessage()    {}
func (*DeleteStorefrontItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{2}
}

func (m *DeleteStorefrontItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorefrontItem.Unmarshal(m, b)
}
func (m *DeleteStorefrontItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorefrontItem.Marshal(b, m, deterministic)
}
func (m *DeleteStorefrontItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorefrontItem.Merge(m, src)
}
func (m *DeleteStorefrontItem) XXX_Size() int {
	return xxx_messageInfo_DeleteStorefrontItem.Size(m)
}
func (m *DeleteStorefrontItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorefrontItem.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorefrontItem proto.InternalMessageInfo

func (m *DeleteStorefrontItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteStorefrontItem) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type AcceptRental struct {
	Uuid                 string         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Rental               *rental.Rental `protobuf:"bytes,2,opt,name=rental,proto3" json:"rental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AcceptRental) Reset()         { *m = AcceptRental{} }
func (m *AcceptRental) String() string { return proto.CompactTextString(m) }
func (*AcceptRental) ProtoMessage()    {}
func (*AcceptRental) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{3}
}

func (m *AcceptRental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptRental.Unmarshal(m, b)
}
func (m *AcceptRental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptRental.Marshal(b, m, deterministic)
}
func (m *AcceptRental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRental.Merge(m, src)
}
func (m *AcceptRental) XXX_Size() int {
	return xxx_messageInfo_AcceptRental.Size(m)
}
func (m *AcceptRental) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRental.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRental proto.InternalMessageInfo

func (m *AcceptRental) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AcceptRental) GetRental() *rental.Rental {
	if m != nil {
		return m.Rental
	}
	return nil
}

type DeclineRental struct {
	Uuid                 string         `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Rental               *rental.Rental `protobuf:"bytes,2,opt,name=rental,proto3" json:"rental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeclineRental) Reset()         { *m = DeclineRental{} }
func (m *DeclineRental) String() string { return proto.CompactTextString(m) }
func (*DeclineRental) ProtoMessage()    {}
func (*DeclineRental) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{4}
}

func (m *DeclineRental) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeclineRental.Unmarshal(m, b)
}
func (m *DeclineRental) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeclineRental.Marshal(b, m, deterministic)
}
func (m *DeclineRental) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeclineRental.Merge(m, src)
}
func (m *DeclineRental) XXX_Size() int {
	return xxx_messageInfo_DeclineRental.Size(m)
}
func (m *DeclineRental) XXX_DiscardUnknown() {
	xxx_messageInfo_DeclineRental.DiscardUnknown(m)
}

var xxx_messageInfo_DeclineRental proto.InternalMessageInfo

func (m *DeclineRental) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeclineRental) GetRental() *rental.Rental {
	if m != nil {
		return m.Rental
	}
	return nil
}

type AddItemToCart struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cart                 *rental.Cart `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	Item                 *rental.Item `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddItemToCart) Reset()         { *m = AddItemToCart{} }
func (m *AddItemToCart) String() string { return proto.CompactTextString(m) }
func (*AddItemToCart) ProtoMessage()    {}
func (*AddItemToCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{5}
}

func (m *AddItemToCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemToCart.Unmarshal(m, b)
}
func (m *AddItemToCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemToCart.Marshal(b, m, deterministic)
}
func (m *AddItemToCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemToCart.Merge(m, src)
}
func (m *AddItemToCart) XXX_Size() int {
	return xxx_messageInfo_AddItemToCart.Size(m)
}
func (m *AddItemToCart) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemToCart.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemToCart proto.InternalMessageInfo

func (m *AddItemToCart) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddItemToCart) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *AddItemToCart) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type EditCartItem struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cart                 *rental.Cart `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditCartItem) Reset()         { *m = EditCartItem{} }
func (m *EditCartItem) String() string { return proto.CompactTextString(m) }
func (*EditCartItem) ProtoMessage()    {}
func (*EditCartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{6}
}

func (m *EditCartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCartItem.Unmarshal(m, b)
}
func (m *EditCartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCartItem.Marshal(b, m, deterministic)
}
func (m *EditCartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCartItem.Merge(m, src)
}
func (m *EditCartItem) XXX_Size() int {
	return xxx_messageInfo_EditCartItem.Size(m)
}
func (m *EditCartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCartItem.DiscardUnknown(m)
}

var xxx_messageInfo_EditCartItem proto.InternalMessageInfo

func (m *EditCartItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EditCartItem) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type DeleteCartItem struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cart                 *rental.Cart `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteCartItem) Reset()         { *m = DeleteCartItem{} }
func (m *DeleteCartItem) String() string { return proto.CompactTextString(m) }
func (*DeleteCartItem) ProtoMessage()    {}
func (*DeleteCartItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{7}
}

func (m *DeleteCartItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCartItem.Unmarshal(m, b)
}
func (m *DeleteCartItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCartItem.Marshal(b, m, deterministic)
}
func (m *DeleteCartItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCartItem.Merge(m, src)
}
func (m *DeleteCartItem) XXX_Size() int {
	return xxx_messageInfo_DeleteCartItem.Size(m)
}
func (m *DeleteCartItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCartItem.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCartItem proto.InternalMessageInfo

func (m *DeleteCartItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteCartItem) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type BookCartItems struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cart                 *rental.Cart `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookCartItems) Reset()         { *m = BookCartItems{} }
func (m *BookCartItems) String() string { return proto.CompactTextString(m) }
func (*BookCartItems) ProtoMessage()    {}
func (*BookCartItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{8}
}

func (m *BookCartItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCartItems.Unmarshal(m, b)
}
func (m *BookCartItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCartItems.Marshal(b, m, deterministic)
}
func (m *BookCartItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCartItems.Merge(m, src)
}
func (m *BookCartItems) XXX_Size() int {
	return xxx_messageInfo_BookCartItems.Size(m)
}
func (m *BookCartItems) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCartItems.DiscardUnknown(m)
}

var xxx_messageInfo_BookCartItems proto.InternalMessageInfo

func (m *BookCartItems) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BookCartItems) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type ContactOwnersForAcceptance struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Users                []*user.User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Cart                 *rental.Cart `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContactOwnersForAcceptance) Reset()         { *m = ContactOwnersForAcceptance{} }
func (m *ContactOwnersForAcceptance) String() string { return proto.CompactTextString(m) }
func (*ContactOwnersForAcceptance) ProtoMessage()    {}
func (*ContactOwnersForAcceptance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0ada4ea19f4162a, []int{9}
}

func (m *ContactOwnersForAcceptance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactOwnersForAcceptance.Unmarshal(m, b)
}
func (m *ContactOwnersForAcceptance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactOwnersForAcceptance.Marshal(b, m, deterministic)
}
func (m *ContactOwnersForAcceptance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactOwnersForAcceptance.Merge(m, src)
}
func (m *ContactOwnersForAcceptance) XXX_Size() int {
	return xxx_messageInfo_ContactOwnersForAcceptance.Size(m)
}
func (m *ContactOwnersForAcceptance) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactOwnersForAcceptance.DiscardUnknown(m)
}

var xxx_messageInfo_ContactOwnersForAcceptance proto.InternalMessageInfo

func (m *ContactOwnersForAcceptance) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ContactOwnersForAcceptance) GetUsers() []*user.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ContactOwnersForAcceptance) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func init() {
	proto.RegisterType((*AddItemToStorefront)(nil), "command.AddItemToStorefront")
	proto.RegisterType((*EditStorefrontItem)(nil), "command.EditStorefrontItem")
	proto.RegisterType((*DeleteStorefrontItem)(nil), "command.DeleteStorefrontItem")
	proto.RegisterType((*AcceptRental)(nil), "command.AcceptRental")
	proto.RegisterType((*DeclineRental)(nil), "command.DeclineRental")
	proto.RegisterType((*AddItemToCart)(nil), "command.AddItemToCart")
	proto.RegisterType((*EditCartItem)(nil), "command.EditCartItem")
	proto.RegisterType((*DeleteCartItem)(nil), "command.DeleteCartItem")
	proto.RegisterType((*BookCartItems)(nil), "command.BookCartItems")
	proto.RegisterType((*ContactOwnersForAcceptance)(nil), "command.ContactOwnersForAcceptance")
}

func init() { proto.RegisterFile("commands/rental.proto", fileDescriptor_e0ada4ea19f4162a) }

var fileDescriptor_e0ada4ea19f4162a = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x8f, 0x12, 0x31,
	0x18, 0xc6, 0x33, 0x3b, 0xeb, 0xae, 0x76, 0xc1, 0xc4, 0x41, 0x22, 0xe2, 0x85, 0xcc, 0x45, 0x2e,
	0xcc, 0x24, 0x78, 0x33, 0x5e, 0xf8, 0xd0, 0xc4, 0xa8, 0x31, 0x16, 0xbd, 0x78, 0x31, 0xa5, 0x7d,
	0x95, 0x86, 0x69, 0x4b, 0xda, 0x8e, 0xdc, 0x3d, 0xf9, 0x67, 0x9b, 0xb6, 0x33, 0x68, 0x08, 0x03,
	0x24, 0x72, 0x99, 0x34, 0xf3, 0x3c, 0xef, 0xaf, 0xef, 0x47, 0x5b, 0xd4, 0xa5, 0x4a, 0x08, 0x22,
	0x99, 0xc9, 0x35, 0x48, 0x4b, 0x8a, 0x6c, 0xa3, 0x95, 0x55, 0xc9, 0x6d, 0xf5, 0xbb, 0xff, 0x84,
	0x29, 0x41, 0xb8, 0x34, 0x79, 0x69, 0x40, 0xfb, 0x4f, 0x70, 0xf4, 0x9f, 0xd6, 0x42, 0x88, 0xcb,
	0xb9, 0x05, 0xd1, 0x20, 0x51, 0xa2, 0x6d, 0x25, 0x3d, 0xdb, 0x93, 0xfe, 0xdd, 0x34, 0xc5, 0xa8,
	0x33, 0x61, 0xec, 0xad, 0x05, 0xf1, 0x59, 0x2d, 0xac, 0xd2, 0xf0, 0x5d, 0x2b, 0x69, 0x93, 0x04,
	0x5d, 0x97, 0x25, 0x67, 0xbd, 0x68, 0x10, 0x0d, 0x1f, 0x60, 0xbf, 0x4e, 0x9e, 0xa3, 0x6b, 0xb7,
	0x61, 0xef, 0x6a, 0x10, 0x0d, 0xef, 0xc6, 0x9d, 0x2c, 0x60, 0xb3, 0x0a, 0xe7, 0x10, 0xd8, 0x1b,
	0xd2, 0xdf, 0x11, 0x4a, 0x5e, 0x33, 0x6e, 0xff, 0xf2, 0x9c, 0x78, 0x90, 0x99, 0xa1, 0xfb, 0xaa,
	0x60, 0xdf, 0x4e, 0x71, 0x6f, 0x55, 0xe1, 0x73, 0x74, 0x7e, 0x09, 0xdb, 0xe0, 0x8f, 0x8f, 0xf8,
	0x25, 0x6c, 0xdd, 0x22, 0x5d, 0xa0, 0xc7, 0x73, 0x28, 0xc0, 0xc2, 0x19, 0xb9, 0xd4, 0xf5, 0xc5,
	0xa7, 0xea, 0xfb, 0x84, 0x5a, 0x13, 0x4a, 0x61, 0x63, 0xb1, 0x97, 0x0e, 0xc2, 0x46, 0xe8, 0x26,
	0x04, 0x56, 0x65, 0x75, 0xf7, 0x70, 0x21, 0x14, 0x57, 0xa6, 0x14, 0xa3, 0xf6, 0x1c, 0x68, 0xc1,
	0x25, 0x5c, 0x8e, 0x59, 0xa2, 0xf6, 0x6e, 0xb4, 0x33, 0xa2, 0x1b, 0x87, 0xea, 0x8e, 0x4a, 0x43,
	0xf3, 0x5d, 0x18, 0xf6, 0x86, 0xf3, 0xbb, 0xf3, 0x0e, 0xb5, 0xdc, 0xf0, 0x5d, 0xe8, 0xb1, 0x56,
	0x9f, 0xb5, 0x6b, 0xfa, 0x01, 0x3d, 0x0c, 0xf3, 0xbb, 0x0c, 0xee, 0x3d, 0x6a, 0x4f, 0x95, 0x5a,
	0xd7, 0x30, 0xf3, 0x7f, 0xb4, 0x5f, 0x11, 0xea, 0xcf, 0x94, 0xb4, 0x84, 0xda, 0x8f, 0x5b, 0x09,
	0xda, 0xbc, 0x51, 0x3a, 0x1c, 0x0c, 0x22, 0x29, 0x34, 0xb0, 0xef, 0xb9, 0xfb, 0x6c, 0x7a, 0x57,
	0x83, 0x78, 0x78, 0x37, 0x7e, 0x54, 0xc3, 0xfd, 0x25, 0xff, 0x62, 0x40, 0xe3, 0xa0, 0xef, 0x92,
	0x88, 0x4f, 0x24, 0x31, 0x7d, 0xf5, 0xf5, 0xe5, 0x0f, 0x6e, 0x57, 0xe5, 0x32, 0xa3, 0x4a, 0xe4,
	0xbc, 0x58, 0x11, 0x21, 0x56, 0x8c, 0xe5, 0xeb, 0x92, 0x91, 0x35, 0x1f, 0x39, 0xda, 0xc8, 0x80,
	0xfe, 0xc9, 0x29, 0xe4, 0x20, 0x2d, 0xb7, 0x1c, 0x4c, 0x5e, 0x3f, 0x40, 0xcb, 0x1b, 0xff, 0x0a,
	0xbc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x7a, 0xe5, 0x1a, 0x93, 0x04, 0x00, 0x00,
}
