// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/user.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUp struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Profile              *user.Profile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	User                 *user.User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SignUp) Reset()         { *m = SignUp{} }
func (m *SignUp) String() string { return proto.CompactTextString(m) }
func (*SignUp) ProtoMessage()    {}
func (*SignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{0}
}

func (m *SignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUp.Unmarshal(m, b)
}
func (m *SignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUp.Marshal(b, m, deterministic)
}
func (m *SignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUp.Merge(m, src)
}
func (m *SignUp) XXX_Size() int {
	return xxx_messageInfo_SignUp.Size(m)
}
func (m *SignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUp proto.InternalMessageInfo

func (m *SignUp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignUp) GetProfile() *user.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SignUp) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignIn struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User                 *user.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignIn) Reset()         { *m = SignIn{} }
func (m *SignIn) String() string { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()    {}
func (*SignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{1}
}

func (m *SignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignIn.Unmarshal(m, b)
}
func (m *SignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignIn.Marshal(b, m, deterministic)
}
func (m *SignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignIn.Merge(m, src)
}
func (m *SignIn) XXX_Size() int {
	return xxx_messageInfo_SignIn.Size(m)
}
func (m *SignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignIn proto.InternalMessageInfo

func (m *SignIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignIn) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignOut struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User                 *user.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignOut) Reset()         { *m = SignOut{} }
func (m *SignOut) String() string { return proto.CompactTextString(m) }
func (*SignOut) ProtoMessage()    {}
func (*SignOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{2}
}

func (m *SignOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOut.Unmarshal(m, b)
}
func (m *SignOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOut.Marshal(b, m, deterministic)
}
func (m *SignOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOut.Merge(m, src)
}
func (m *SignOut) XXX_Size() int {
	return xxx_messageInfo_SignOut.Size(m)
}
func (m *SignOut) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOut.DiscardUnknown(m)
}

var xxx_messageInfo_SignOut proto.InternalMessageInfo

func (m *SignOut) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignOut) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteAccount struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User                 *user.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteAccount) Reset()         { *m = DeleteAccount{} }
func (m *DeleteAccount) String() string { return proto.CompactTextString(m) }
func (*DeleteAccount) ProtoMessage()    {}
func (*DeleteAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{3}
}

func (m *DeleteAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccount.Unmarshal(m, b)
}
func (m *DeleteAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccount.Marshal(b, m, deterministic)
}
func (m *DeleteAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccount.Merge(m, src)
}
func (m *DeleteAccount) XXX_Size() int {
	return xxx_messageInfo_DeleteAccount.Size(m)
}
func (m *DeleteAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccount proto.InternalMessageInfo

func (m *DeleteAccount) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteAccount) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateProfile struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NewProfile           *user.Profile `protobuf:"bytes,3,opt,name=new_profile,json=newProfile,proto3" json:"new_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateProfile) Reset()         { *m = UpdateProfile{} }
func (m *UpdateProfile) String() string { return proto.CompactTextString(m) }
func (*UpdateProfile) ProtoMessage()    {}
func (*UpdateProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{4}
}

func (m *UpdateProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfile.Unmarshal(m, b)
}
func (m *UpdateProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfile.Marshal(b, m, deterministic)
}
func (m *UpdateProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfile.Merge(m, src)
}
func (m *UpdateProfile) XXX_Size() int {
	return xxx_messageInfo_UpdateProfile.Size(m)
}
func (m *UpdateProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfile proto.InternalMessageInfo

func (m *UpdateProfile) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateProfile) GetNewProfile() *user.Profile {
	if m != nil {
		return m.NewProfile
	}
	return nil
}

type ChangePassword struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	NewUser              *user.User `protobuf:"bytes,3,opt,name=new_user,json=newUser,proto3" json:"new_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChangePassword) Reset()         { *m = ChangePassword{} }
func (m *ChangePassword) String() string { return proto.CompactTextString(m) }
func (*ChangePassword) ProtoMessage()    {}
func (*ChangePassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{5}
}

func (m *ChangePassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePassword.Unmarshal(m, b)
}
func (m *ChangePassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePassword.Marshal(b, m, deterministic)
}
func (m *ChangePassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePassword.Merge(m, src)
}
func (m *ChangePassword) XXX_Size() int {
	return xxx_messageInfo_ChangePassword.Size(m)
}
func (m *ChangePassword) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePassword.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePassword proto.InternalMessageInfo

func (m *ChangePassword) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ChangePassword) GetNewUser() *user.User {
	if m != nil {
		return m.NewUser
	}
	return nil
}

type SearchUsers struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUsers) Reset()         { *m = SearchUsers{} }
func (m *SearchUsers) String() string { return proto.CompactTextString(m) }
func (*SearchUsers) ProtoMessage()    {}
func (*SearchUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{6}
}

func (m *SearchUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUsers.Unmarshal(m, b)
}
func (m *SearchUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUsers.Marshal(b, m, deterministic)
}
func (m *SearchUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUsers.Merge(m, src)
}
func (m *SearchUsers) XXX_Size() int {
	return xxx_messageInfo_SearchUsers.Size(m)
}
func (m *SearchUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUsers.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUsers proto.InternalMessageInfo

func (m *SearchUsers) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SearchUsers) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type MakePayment struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Payment              *user.Payment `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MakePayment) Reset()         { *m = MakePayment{} }
func (m *MakePayment) String() string { return proto.CompactTextString(m) }
func (*MakePayment) ProtoMessage()    {}
func (*MakePayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_781b635963ffb5d5, []int{7}
}

func (m *MakePayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakePayment.Unmarshal(m, b)
}
func (m *MakePayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakePayment.Marshal(b, m, deterministic)
}
func (m *MakePayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakePayment.Merge(m, src)
}
func (m *MakePayment) XXX_Size() int {
	return xxx_messageInfo_MakePayment.Size(m)
}
func (m *MakePayment) XXX_DiscardUnknown() {
	xxx_messageInfo_MakePayment.DiscardUnknown(m)
}

var xxx_messageInfo_MakePayment proto.InternalMessageInfo

func (m *MakePayment) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MakePayment) GetPayment() *user.Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*SignUp)(nil), "command.SignUp")
	proto.RegisterType((*SignIn)(nil), "command.SignIn")
	proto.RegisterType((*SignOut)(nil), "command.SignOut")
	proto.RegisterType((*DeleteAccount)(nil), "command.DeleteAccount")
	proto.RegisterType((*UpdateProfile)(nil), "command.UpdateProfile")
	proto.RegisterType((*ChangePassword)(nil), "command.ChangePassword")
	proto.RegisterType((*SearchUsers)(nil), "command.SearchUsers")
	proto.RegisterType((*MakePayment)(nil), "command.MakePayment")
}

func init() { proto.RegisterFile("commands/user.proto", fileDescriptor_781b635963ffb5d5) }

var fileDescriptor_781b635963ffb5d5 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6b, 0xea, 0x40,
	0x10, 0xc7, 0xf1, 0x07, 0xe6, 0x39, 0xc1, 0xc7, 0x7b, 0x69, 0xa1, 0xe2, 0x49, 0x02, 0x05, 0x0f,
	0x35, 0x81, 0x4a, 0x2f, 0xa5, 0x97, 0x56, 0x2f, 0x2d, 0x94, 0xda, 0x88, 0x17, 0x2f, 0x65, 0xcd,
	0x4e, 0xcd, 0x12, 0xb3, 0x1b, 0xb2, 0x9b, 0x06, 0xff, 0xfb, 0xb2, 0xd9, 0x04, 0x2a, 0xa4, 0x5e,
	0xbc, 0x4d, 0xf2, 0xf9, 0xe6, 0x33, 0x64, 0x76, 0x16, 0x2e, 0x42, 0x91, 0x24, 0x84, 0x53, 0xe9,
	0xe7, 0x12, 0x33, 0x2f, 0xcd, 0x84, 0x12, 0x8e, 0x55, 0xbd, 0x1c, 0x5d, 0x51, 0x91, 0x10, 0xc6,
	0x0d, 0xfc, 0x91, 0x18, 0x8d, 0x8e, 0x40, 0x9a, 0x89, 0x4f, 0xb6, 0xc7, 0x66, 0x46, 0x0e, 0x09,
	0x72, 0x65, 0x98, 0x2b, 0xa1, 0xb7, 0x62, 0x3b, 0xbe, 0x4e, 0x1d, 0x07, 0xba, 0x79, 0xce, 0xe8,
	0xb0, 0x35, 0x6e, 0x4d, 0xfa, 0x41, 0x59, 0x3b, 0x1e, 0x58, 0x95, 0x6a, 0xd8, 0x1e, 0xb7, 0x26,
	0xf6, 0xed, 0xa5, 0x67, 0x5c, 0x5e, 0xd9, 0x7a, 0x69, 0x58, 0x50, 0x87, 0x9c, 0x6b, 0xe8, 0x6a,
	0x30, 0xec, 0x94, 0xe1, 0xff, 0x47, 0xe1, 0xb5, 0xc4, 0x2c, 0x28, 0xb1, 0x3b, 0x37, 0x4d, 0x9f,
	0x79, 0x63, 0xd3, 0x5a, 0xd2, 0x3e, 0x2d, 0x59, 0x80, 0xa5, 0x25, 0x6f, 0xb9, 0x3a, 0xc7, 0xf2,
	0x02, 0x83, 0x05, 0xee, 0x51, 0xe1, 0x63, 0x18, 0x8a, 0x9c, 0x9f, 0xe5, 0xda, 0xc0, 0x60, 0x9d,
	0x52, 0xa2, 0xb0, 0x9a, 0x4b, 0xa3, 0xeb, 0x0e, 0x6c, 0x8e, 0xc5, 0x47, 0x3d, 0xd6, 0xce, 0x89,
	0xb1, 0x02, 0xc7, 0xa2, 0xaa, 0xdd, 0x00, 0xfe, 0xce, 0x23, 0xc2, 0x77, 0xb8, 0x24, 0x52, 0x16,
	0x22, 0xa3, 0x8d, 0xf2, 0x1b, 0xf8, 0xa3, 0xe5, 0xa7, 0xcf, 0xc0, 0xe2, 0x58, 0xe8, 0xc2, 0x9d,
	0x81, 0xbd, 0x42, 0x92, 0x85, 0x91, 0x7e, 0x92, 0x8d, 0xc2, 0x7f, 0xd0, 0x89, 0xf1, 0x50, 0xfe,
	0x78, 0x3f, 0xd0, 0xa5, 0xfb, 0x0e, 0xf6, 0x2b, 0x89, 0x71, 0x69, 0xb6, 0xe8, 0xd7, 0xad, 0x31,
	0xb8, 0x79, 0x6b, 0x0c, 0x0b, 0xea, 0xd0, 0xd3, 0xc3, 0xe6, 0x7e, 0xc7, 0x54, 0x94, 0x6f, 0xbd,
	0x50, 0x24, 0x3e, 0xdb, 0x47, 0x24, 0x49, 0x22, 0x4a, 0xfd, 0x38, 0xa7, 0x24, 0x66, 0x53, 0xfd,
	0xd1, 0x54, 0x62, 0xf6, 0xc5, 0x42, 0xf4, 0x91, 0x2b, 0xa6, 0x18, 0x4a, 0xbf, 0xbe, 0x26, 0xdb,
	0x5e, 0xb9, 0xc8, 0xb3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0xc4, 0xcb, 0x15, 0x39, 0x03,
	0x00, 0x00,
}
