// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queries/kudaki_event.proto

package queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveEventAds struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveEventAds) Reset()         { *m = RetrieveEventAds{} }
func (m *RetrieveEventAds) String() string { return proto.CompactTextString(m) }
func (*RetrieveEventAds) ProtoMessage()    {}
func (*RetrieveEventAds) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{0}
}

func (m *RetrieveEventAds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveEventAds.Unmarshal(m, b)
}
func (m *RetrieveEventAds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveEventAds.Marshal(b, m, deterministic)
}
func (m *RetrieveEventAds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveEventAds.Merge(m, src)
}
func (m *RetrieveEventAds) XXX_Size() int {
	return xxx_messageInfo_RetrieveEventAds.Size(m)
}
func (m *RetrieveEventAds) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveEventAds.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveEventAds proto.InternalMessageInfo

func (m *RetrieveEventAds) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveEventAds) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveEventAd struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventAdUuid          string   `protobuf:"bytes,2,opt,name=event_ad_uuid,json=eventAdUuid,proto3" json:"event_ad_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveEventAd) Reset()         { *m = RetrieveEventAd{} }
func (m *RetrieveEventAd) String() string { return proto.CompactTextString(m) }
func (*RetrieveEventAd) ProtoMessage()    {}
func (*RetrieveEventAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{1}
}

func (m *RetrieveEventAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveEventAd.Unmarshal(m, b)
}
func (m *RetrieveEventAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveEventAd.Marshal(b, m, deterministic)
}
func (m *RetrieveEventAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveEventAd.Merge(m, src)
}
func (m *RetrieveEventAd) XXX_Size() int {
	return xxx_messageInfo_RetrieveEventAd.Size(m)
}
func (m *RetrieveEventAd) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveEventAd.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveEventAd proto.InternalMessageInfo

func (m *RetrieveEventAd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveEventAd) GetEventAdUuid() string {
	if m != nil {
		return m.EventAdUuid
	}
	return ""
}

type SearchEventAd struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchEventAd) Reset()         { *m = SearchEventAd{} }
func (m *SearchEventAd) String() string { return proto.CompactTextString(m) }
func (*SearchEventAd) ProtoMessage()    {}
func (*SearchEventAd) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{2}
}

func (m *SearchEventAd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchEventAd.Unmarshal(m, b)
}
func (m *SearchEventAd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchEventAd.Marshal(b, m, deterministic)
}
func (m *SearchEventAd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchEventAd.Merge(m, src)
}
func (m *SearchEventAd) XXX_Size() int {
	return xxx_messageInfo_SearchEventAd.Size(m)
}
func (m *SearchEventAd) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchEventAd.DiscardUnknown(m)
}

var xxx_messageInfo_SearchEventAd proto.InternalMessageInfo

func (m *SearchEventAd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SearchEventAd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RetrieveOrganizers struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveOrganizers) Reset()         { *m = RetrieveOrganizers{} }
func (m *RetrieveOrganizers) String() string { return proto.CompactTextString(m) }
func (*RetrieveOrganizers) ProtoMessage()    {}
func (*RetrieveOrganizers) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{3}
}

func (m *RetrieveOrganizers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOrganizers.Unmarshal(m, b)
}
func (m *RetrieveOrganizers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOrganizers.Marshal(b, m, deterministic)
}
func (m *RetrieveOrganizers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOrganizers.Merge(m, src)
}
func (m *RetrieveOrganizers) XXX_Size() int {
	return xxx_messageInfo_RetrieveOrganizers.Size(m)
}
func (m *RetrieveOrganizers) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOrganizers.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOrganizers proto.InternalMessageInfo

func (m *RetrieveOrganizers) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveOrganizers) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveOrganizer struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	OrganizerUuid        string   `protobuf:"bytes,2,opt,name=organizer_uuid,json=organizerUuid,proto3" json:"organizer_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveOrganizer) Reset()         { *m = RetrieveOrganizer{} }
func (m *RetrieveOrganizer) String() string { return proto.CompactTextString(m) }
func (*RetrieveOrganizer) ProtoMessage()    {}
func (*RetrieveOrganizer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{4}
}

func (m *RetrieveOrganizer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOrganizer.Unmarshal(m, b)
}
func (m *RetrieveOrganizer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOrganizer.Marshal(b, m, deterministic)
}
func (m *RetrieveOrganizer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOrganizer.Merge(m, src)
}
func (m *RetrieveOrganizer) XXX_Size() int {
	return xxx_messageInfo_RetrieveOrganizer.Size(m)
}
func (m *RetrieveOrganizer) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOrganizer.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOrganizer proto.InternalMessageInfo

func (m *RetrieveOrganizer) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveOrganizer) GetOrganizerUuid() string {
	if m != nil {
		return m.OrganizerUuid
	}
	return ""
}

type SearchOrganizer struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchOrganizer) Reset()         { *m = SearchOrganizer{} }
func (m *SearchOrganizer) String() string { return proto.CompactTextString(m) }
func (*SearchOrganizer) ProtoMessage()    {}
func (*SearchOrganizer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd49f87a1119bd1, []int{5}
}

func (m *SearchOrganizer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOrganizer.Unmarshal(m, b)
}
func (m *SearchOrganizer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOrganizer.Marshal(b, m, deterministic)
}
func (m *SearchOrganizer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOrganizer.Merge(m, src)
}
func (m *SearchOrganizer) XXX_Size() int {
	return xxx_messageInfo_SearchOrganizer.Size(m)
}
func (m *SearchOrganizer) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOrganizer.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOrganizer proto.InternalMessageInfo

func (m *SearchOrganizer) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SearchOrganizer) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrieveEventAds)(nil), "query.RetrieveEventAds")
	proto.RegisterType((*RetrieveEventAd)(nil), "query.RetrieveEventAd")
	proto.RegisterType((*SearchEventAd)(nil), "query.SearchEventAd")
	proto.RegisterType((*RetrieveOrganizers)(nil), "query.RetrieveOrganizers")
	proto.RegisterType((*RetrieveOrganizer)(nil), "query.RetrieveOrganizer")
	proto.RegisterType((*SearchOrganizer)(nil), "query.SearchOrganizer")
}

func init() { proto.RegisterFile("queries/kudaki_event.proto", fileDescriptor_1fd49f87a1119bd1) }

var fileDescriptor_1fd49f87a1119bd1 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xbf, 0x5f, 0x0b, 0x4e, 0x49, 0x5b, 0x83, 0x87, 0xd2, 0x53, 0x09, 0x28, 0xbd,
	0x34, 0x01, 0x45, 0x44, 0x3c, 0x29, 0x28, 0x78, 0xa9, 0x12, 0xf1, 0xe2, 0x25, 0x6c, 0xb3, 0x63,
	0x33, 0xa4, 0xc9, 0xea, 0xfe, 0x08, 0xd4, 0xbf, 0x5e, 0xb2, 0x9b, 0x8a, 0xd8, 0xd2, 0x8b, 0xb7,
	0x61, 0xde, 0xbc, 0x0f, 0xf3, 0x98, 0x81, 0xf1, 0x87, 0x41, 0x49, 0xa8, 0xe2, 0xc2, 0x70, 0x56,
	0x50, 0x8a, 0x35, 0x56, 0x3a, 0x7a, 0x97, 0x42, 0x8b, 0xe0, 0xa0, 0xd1, 0xd6, 0xe3, 0x63, 0x2e,
	0x4a, 0x46, 0x95, 0x8a, 0xdf, 0x68, 0xa5, 0x51, 0x3a, 0x31, 0x9c, 0xc3, 0x30, 0x41, 0x2d, 0x09,
	0x6b, 0xbc, 0x6b, 0x3c, 0x37, 0x5c, 0x05, 0x01, 0xfc, 0x37, 0x86, 0xf8, 0xc8, 0x9b, 0x78, 0xd3,
	0xc3, 0xc4, 0xd6, 0xc1, 0x29, 0x74, 0x9d, 0x6f, 0xd4, 0x99, 0x78, 0xd3, 0xde, 0x59, 0x3f, 0x72,
	0xb8, 0xe8, 0xde, 0x76, 0x93, 0x56, 0x0d, 0x1f, 0x60, 0xf0, 0x8b, 0xb7, 0x13, 0x17, 0x82, 0x6f,
	0x57, 0x4c, 0x19, 0x4f, 0xad, 0xd8, 0xb1, 0x62, 0x0f, 0x9d, 0xe7, 0xc5, 0x10, 0x0f, 0x2f, 0xc0,
	0x7f, 0x46, 0x26, 0xb3, 0x7c, 0x1f, 0x68, 0x08, 0xff, 0x0a, 0x5c, 0xb7, 0xf6, 0xa6, 0x0c, 0x9f,
	0x20, 0xd8, 0x6c, 0xf0, 0x28, 0x97, 0xac, 0xa2, 0x4f, 0x94, 0x7f, 0xcb, 0x34, 0x87, 0xa3, 0x2d,
	0xe2, 0x4e, 0xe0, 0x09, 0xf4, 0xc5, 0x66, 0xe0, 0x67, 0x2c, 0xff, 0xbb, 0x6b, 0x83, 0x5d, 0xc2,
	0xc0, 0x05, 0xdb, 0x4f, 0xdb, 0x8a, 0x76, 0x7b, 0xfd, 0x7a, 0xb5, 0x24, 0x9d, 0x9b, 0x45, 0x94,
	0x89, 0x32, 0xa6, 0x55, 0xce, 0xca, 0x32, 0xe7, 0xbc, 0x3d, 0xfa, 0xcc, 0x28, 0x94, 0x33, 0x85,
	0xb2, 0xa6, 0x0c, 0x63, 0xac, 0x34, 0xe9, 0xe6, 0x23, 0xda, 0xcf, 0x58, 0x74, 0xed, 0xc1, 0xcf,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0x38, 0x8c, 0xbb, 0x2b, 0x02, 0x00, 0x00,
}
