// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queries/mountain.proto

package queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	mountain "github.com/ilhammhdd/kudaki-user-service/entities/domains/mountain"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveMountains struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveMountains) Reset()         { *m = RetrieveMountains{} }
func (m *RetrieveMountains) String() string { return proto.CompactTextString(m) }
func (*RetrieveMountains) ProtoMessage()    {}
func (*RetrieveMountains) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{0}
}

func (m *RetrieveMountains) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveMountains.Unmarshal(m, b)
}
func (m *RetrieveMountains) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveMountains.Marshal(b, m, deterministic)
}
func (m *RetrieveMountains) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveMountains.Merge(m, src)
}
func (m *RetrieveMountains) XXX_Size() int {
	return xxx_messageInfo_RetrieveMountains.Size(m)
}
func (m *RetrieveMountains) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveMountains.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveMountains proto.InternalMessageInfo

func (m *RetrieveMountains) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveMountains) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveMountain struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MountainUuid         string   `protobuf:"bytes,2,opt,name=mountain_uuid,json=mountainUuid,proto3" json:"mountain_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveMountain) Reset()         { *m = RetrieveMountain{} }
func (m *RetrieveMountain) String() string { return proto.CompactTextString(m) }
func (*RetrieveMountain) ProtoMessage()    {}
func (*RetrieveMountain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{1}
}

func (m *RetrieveMountain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveMountain.Unmarshal(m, b)
}
func (m *RetrieveMountain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveMountain.Marshal(b, m, deterministic)
}
func (m *RetrieveMountain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveMountain.Merge(m, src)
}
func (m *RetrieveMountain) XXX_Size() int {
	return xxx_messageInfo_RetrieveMountain.Size(m)
}
func (m *RetrieveMountain) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveMountain.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveMountain proto.InternalMessageInfo

func (m *RetrieveMountain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveMountain) GetMountainUuid() string {
	if m != nil {
		return m.MountainUuid
	}
	return ""
}

type SearchMountain struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchMountain) Reset()         { *m = SearchMountain{} }
func (m *SearchMountain) String() string { return proto.CompactTextString(m) }
func (*SearchMountain) ProtoMessage()    {}
func (*SearchMountain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{2}
}

func (m *SearchMountain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMountain.Unmarshal(m, b)
}
func (m *SearchMountain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMountain.Marshal(b, m, deterministic)
}
func (m *SearchMountain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMountain.Merge(m, src)
}
func (m *SearchMountain) XXX_Size() int {
	return xxx_messageInfo_SearchMountain.Size(m)
}
func (m *SearchMountain) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMountain.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMountain proto.InternalMessageInfo

func (m *SearchMountain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SearchMountain) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RetrieveMountainReviews struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter    `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Mountain             *mountain.Mountain `protobuf:"bytes,3,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RetrieveMountainReviews) Reset()         { *m = RetrieveMountainReviews{} }
func (m *RetrieveMountainReviews) String() string { return proto.CompactTextString(m) }
func (*RetrieveMountainReviews) ProtoMessage()    {}
func (*RetrieveMountainReviews) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{3}
}

func (m *RetrieveMountainReviews) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveMountainReviews.Unmarshal(m, b)
}
func (m *RetrieveMountainReviews) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveMountainReviews.Marshal(b, m, deterministic)
}
func (m *RetrieveMountainReviews) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveMountainReviews.Merge(m, src)
}
func (m *RetrieveMountainReviews) XXX_Size() int {
	return xxx_messageInfo_RetrieveMountainReviews.Size(m)
}
func (m *RetrieveMountainReviews) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveMountainReviews.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveMountainReviews proto.InternalMessageInfo

func (m *RetrieveMountainReviews) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveMountainReviews) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RetrieveMountainReviews) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type RetrieveRecomendedGears struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter    `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Mountain             *mountain.Mountain `protobuf:"bytes,3,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RetrieveRecomendedGears) Reset()         { *m = RetrieveRecomendedGears{} }
func (m *RetrieveRecomendedGears) String() string { return proto.CompactTextString(m) }
func (*RetrieveRecomendedGears) ProtoMessage()    {}
func (*RetrieveRecomendedGears) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{4}
}

func (m *RetrieveRecomendedGears) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRecomendedGears.Unmarshal(m, b)
}
func (m *RetrieveRecomendedGears) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRecomendedGears.Marshal(b, m, deterministic)
}
func (m *RetrieveRecomendedGears) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRecomendedGears.Merge(m, src)
}
func (m *RetrieveRecomendedGears) XXX_Size() int {
	return xxx_messageInfo_RetrieveRecomendedGears.Size(m)
}
func (m *RetrieveRecomendedGears) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRecomendedGears.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRecomendedGears proto.InternalMessageInfo

func (m *RetrieveRecomendedGears) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveRecomendedGears) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RetrieveRecomendedGears) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type RetrieveRecomendedGear struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RecomendedGearUuid   string   `protobuf:"bytes,2,opt,name=recomended_gear_uuid,json=recomendedGearUuid,proto3" json:"recomended_gear_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveRecomendedGear) Reset()         { *m = RetrieveRecomendedGear{} }
func (m *RetrieveRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*RetrieveRecomendedGear) ProtoMessage()    {}
func (*RetrieveRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{5}
}

func (m *RetrieveRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRecomendedGear.Unmarshal(m, b)
}
func (m *RetrieveRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRecomendedGear.Marshal(b, m, deterministic)
}
func (m *RetrieveRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRecomendedGear.Merge(m, src)
}
func (m *RetrieveRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_RetrieveRecomendedGear.Size(m)
}
func (m *RetrieveRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRecomendedGear proto.InternalMessageInfo

func (m *RetrieveRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveRecomendedGear) GetRecomendedGearUuid() string {
	if m != nil {
		return m.RecomendedGearUuid
	}
	return ""
}

type SearchRecomendedGear struct {
	Uuid                 string             `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Key                  string             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Mountain             *mountain.Mountain `protobuf:"bytes,3,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchRecomendedGear) Reset()         { *m = SearchRecomendedGear{} }
func (m *SearchRecomendedGear) String() string { return proto.CompactTextString(m) }
func (*SearchRecomendedGear) ProtoMessage()    {}
func (*SearchRecomendedGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{6}
}

func (m *SearchRecomendedGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRecomendedGear.Unmarshal(m, b)
}
func (m *SearchRecomendedGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRecomendedGear.Marshal(b, m, deterministic)
}
func (m *SearchRecomendedGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRecomendedGear.Merge(m, src)
}
func (m *SearchRecomendedGear) XXX_Size() int {
	return xxx_messageInfo_SearchRecomendedGear.Size(m)
}
func (m *SearchRecomendedGear) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRecomendedGear.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRecomendedGear proto.InternalMessageInfo

func (m *SearchRecomendedGear) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SearchRecomendedGear) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SearchRecomendedGear) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type RetrieveTrips struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveTrips) Reset()         { *m = RetrieveTrips{} }
func (m *RetrieveTrips) String() string { return proto.CompactTextString(m) }
func (*RetrieveTrips) ProtoMessage()    {}
func (*RetrieveTrips) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba7e3d610bfb7844, []int{7}
}

func (m *RetrieveTrips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTrips.Unmarshal(m, b)
}
func (m *RetrieveTrips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTrips.Marshal(b, m, deterministic)
}
func (m *RetrieveTrips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTrips.Merge(m, src)
}
func (m *RetrieveTrips) XXX_Size() int {
	return xxx_messageInfo_RetrieveTrips.Size(m)
}
func (m *RetrieveTrips) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTrips.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTrips proto.InternalMessageInfo

func (m *RetrieveTrips) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveTrips) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*RetrieveMountains)(nil), "query.RetrieveMountains")
	proto.RegisterType((*RetrieveMountain)(nil), "query.RetrieveMountain")
	proto.RegisterType((*SearchMountain)(nil), "query.SearchMountain")
	proto.RegisterType((*RetrieveMountainReviews)(nil), "query.RetrieveMountainReviews")
	proto.RegisterType((*RetrieveRecomendedGears)(nil), "query.RetrieveRecomendedGears")
	proto.RegisterType((*RetrieveRecomendedGear)(nil), "query.RetrieveRecomendedGear")
	proto.RegisterType((*SearchRecomendedGear)(nil), "query.SearchRecomendedGear")
	proto.RegisterType((*RetrieveTrips)(nil), "query.RetrieveTrips")
}

func init() { proto.RegisterFile("queries/mountain.proto", fileDescriptor_ba7e3d610bfb7844) }

var fileDescriptor_ba7e3d610bfb7844 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0xed, 0xef, 0x57, 0x74, 0xb4, 0xa5, 0x86, 0x52, 0x6b, 0x2f, 0x96, 0x08, 0xd2, 0x4b,
	0x13, 0x51, 0x14, 0xc4, 0x9b, 0x07, 0x3d, 0x14, 0x11, 0xa2, 0x5e, 0x3c, 0x58, 0xb6, 0xd9, 0xb1,
	0x19, 0xda, 0x24, 0x75, 0xb3, 0x5b, 0xe9, 0x77, 0xf0, 0x43, 0x4b, 0x37, 0x7f, 0xb4, 0x35, 0x88,
	0xd8, 0x83, 0xb7, 0xe5, 0xbd, 0x97, 0x97, 0x37, 0xf3, 0x18, 0x68, 0xbe, 0x28, 0x14, 0x84, 0xb1,
	0x13, 0x44, 0x2a, 0x94, 0x8c, 0x42, 0x7b, 0x2a, 0x22, 0x19, 0x99, 0xff, 0x17, 0xf8, 0xbc, 0xbd,
	0xcf, 0xa3, 0x80, 0x51, 0xf8, 0x41, 0xaf, 0xe8, 0xda, 0x8d, 0x4c, 0xf0, 0x4c, 0x13, 0x89, 0x22,
	0x41, 0xad, 0x5b, 0xd8, 0x71, 0x51, 0x0a, 0xc2, 0x19, 0xde, 0xa4, 0xfa, 0xd8, 0x34, 0xe1, 0x9f,
	0x52, 0xc4, 0x5b, 0x46, 0xc7, 0xe8, 0x6e, 0xba, 0xfa, 0x6d, 0x1e, 0x42, 0x25, 0xf9, 0xb0, 0x55,
	0xea, 0x18, 0xdd, 0xad, 0xe3, 0x9a, 0x9d, 0xf8, 0xd9, 0x57, 0x1a, 0x75, 0x53, 0xd6, 0xea, 0x43,
	0x7d, 0xd5, 0xb0, 0xd0, 0xef, 0x00, 0xaa, 0x59, 0xc0, 0x81, 0x26, 0x4b, 0x9a, 0xdc, 0xce, 0xc0,
	0x07, 0x45, 0xdc, 0x3a, 0x83, 0xda, 0x1d, 0x32, 0xe1, 0xf9, 0xdf, 0x5a, 0xd5, 0xa1, 0x3c, 0xc6,
	0x79, 0x6a, 0xb0, 0x78, 0x5a, 0x6f, 0x06, 0xec, 0xae, 0xa6, 0x70, 0x71, 0x46, 0xf8, 0xba, 0xd6,
	0x70, 0xe6, 0x29, 0x6c, 0x64, 0xf9, 0x5a, 0x65, 0xad, 0xdc, 0xcb, 0x94, 0xf9, 0xb6, 0xf3, 0xff,
	0xe5, 0xd2, 0xa5, 0x38, 0x2e, 0x7a, 0x51, 0x80, 0x21, 0x47, 0x7e, 0x8d, 0x4c, 0xfc, 0x49, 0x9c,
	0x27, 0x68, 0x16, 0xa7, 0x29, 0x0c, 0x73, 0x04, 0x0d, 0x91, 0xab, 0x06, 0x23, 0x64, 0xe2, 0x73,
	0x5f, 0xa6, 0x58, 0x72, 0xd0, 0xad, 0xc5, 0xd0, 0x48, 0x5a, 0xfb, 0x81, 0xfb, 0x97, 0xee, 0x7e,
	0x3b, 0x54, 0x1f, 0xaa, 0xd9, 0x50, 0xf7, 0x82, 0xa6, 0x6b, 0x2d, 0xf6, 0xf2, 0xe2, 0xf1, 0x7c,
	0x44, 0xd2, 0x57, 0x43, 0xdb, 0x8b, 0x02, 0x87, 0x26, 0x3e, 0x0b, 0x02, 0x9f, 0x73, 0x67, 0xac,
	0x38, 0x1b, 0x53, 0x4f, 0xc5, 0x28, 0x7a, 0x31, 0x8a, 0x19, 0x79, 0xe8, 0x60, 0x28, 0x49, 0x2e,
	0xee, 0x32, 0xbd, 0xcf, 0x61, 0x45, 0x5f, 0xd6, 0xc9, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51,
	0x3d, 0xca, 0x6d, 0xb1, 0x03, 0x00, 0x00,
}
