// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queries/rental.proto

package queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetrieveStorefrontItems struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserUuid             string          `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveStorefrontItems) Reset()         { *m = RetrieveStorefrontItems{} }
func (m *RetrieveStorefrontItems) String() string { return proto.CompactTextString(m) }
func (*RetrieveStorefrontItems) ProtoMessage()    {}
func (*RetrieveStorefrontItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff488d7bb5d7fae2, []int{0}
}

func (m *RetrieveStorefrontItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveStorefrontItems.Unmarshal(m, b)
}
func (m *RetrieveStorefrontItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveStorefrontItems.Marshal(b, m, deterministic)
}
func (m *RetrieveStorefrontItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveStorefrontItems.Merge(m, src)
}
func (m *RetrieveStorefrontItems) XXX_Size() int {
	return xxx_messageInfo_RetrieveStorefrontItems.Size(m)
}
func (m *RetrieveStorefrontItems) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveStorefrontItems.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveStorefrontItems proto.InternalMessageInfo

func (m *RetrieveStorefrontItems) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveStorefrontItems) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *RetrieveStorefrontItems) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveRentalsHistory struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserUuid             string          `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveRentalsHistory) Reset()         { *m = RetrieveRentalsHistory{} }
func (m *RetrieveRentalsHistory) String() string { return proto.CompactTextString(m) }
func (*RetrieveRentalsHistory) ProtoMessage()    {}
func (*RetrieveRentalsHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff488d7bb5d7fae2, []int{1}
}

func (m *RetrieveRentalsHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRentalsHistory.Unmarshal(m, b)
}
func (m *RetrieveRentalsHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRentalsHistory.Marshal(b, m, deterministic)
}
func (m *RetrieveRentalsHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRentalsHistory.Merge(m, src)
}
func (m *RetrieveRentalsHistory) XXX_Size() int {
	return xxx_messageInfo_RetrieveRentalsHistory.Size(m)
}
func (m *RetrieveRentalsHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRentalsHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRentalsHistory proto.InternalMessageInfo

func (m *RetrieveRentalsHistory) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveRentalsHistory) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *RetrieveRentalsHistory) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveRentalHistory struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RentalUuid           string   `protobuf:"bytes,2,opt,name=rental_uuid,json=rentalUuid,proto3" json:"rental_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveRentalHistory) Reset()         { *m = RetrieveRentalHistory{} }
func (m *RetrieveRentalHistory) String() string { return proto.CompactTextString(m) }
func (*RetrieveRentalHistory) ProtoMessage()    {}
func (*RetrieveRentalHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff488d7bb5d7fae2, []int{2}
}

func (m *RetrieveRentalHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRentalHistory.Unmarshal(m, b)
}
func (m *RetrieveRentalHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRentalHistory.Marshal(b, m, deterministic)
}
func (m *RetrieveRentalHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRentalHistory.Merge(m, src)
}
func (m *RetrieveRentalHistory) XXX_Size() int {
	return xxx_messageInfo_RetrieveRentalHistory.Size(m)
}
func (m *RetrieveRentalHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRentalHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRentalHistory proto.InternalMessageInfo

func (m *RetrieveRentalHistory) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveRentalHistory) GetRentalUuid() string {
	if m != nil {
		return m.RentalUuid
	}
	return ""
}

type RetrieveCartItems struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserUuid             string          `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RetrieveCartItems) Reset()         { *m = RetrieveCartItems{} }
func (m *RetrieveCartItems) String() string { return proto.CompactTextString(m) }
func (*RetrieveCartItems) ProtoMessage()    {}
func (*RetrieveCartItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff488d7bb5d7fae2, []int{3}
}

func (m *RetrieveCartItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveCartItems.Unmarshal(m, b)
}
func (m *RetrieveCartItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveCartItems.Marshal(b, m, deterministic)
}
func (m *RetrieveCartItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveCartItems.Merge(m, src)
}
func (m *RetrieveCartItems) XXX_Size() int {
	return xxx_messageInfo_RetrieveCartItems.Size(m)
}
func (m *RetrieveCartItems) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveCartItems.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveCartItems proto.InternalMessageInfo

func (m *RetrieveCartItems) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveCartItems) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *RetrieveCartItems) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetrieveItem struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ItemUuid             string   `protobuf:"bytes,2,opt,name=item_uuid,json=itemUuid,proto3" json:"item_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveItem) Reset()         { *m = RetrieveItem{} }
func (m *RetrieveItem) String() string { return proto.CompactTextString(m) }
func (*RetrieveItem) ProtoMessage()    {}
func (*RetrieveItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff488d7bb5d7fae2, []int{4}
}

func (m *RetrieveItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveItem.Unmarshal(m, b)
}
func (m *RetrieveItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveItem.Marshal(b, m, deterministic)
}
func (m *RetrieveItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveItem.Merge(m, src)
}
func (m *RetrieveItem) XXX_Size() int {
	return xxx_messageInfo_RetrieveItem.Size(m)
}
func (m *RetrieveItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveItem.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveItem proto.InternalMessageInfo

func (m *RetrieveItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RetrieveItem) GetItemUuid() string {
	if m != nil {
		return m.ItemUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*RetrieveStorefrontItems)(nil), "query.RetrieveStorefrontItems")
	proto.RegisterType((*RetrieveRentalsHistory)(nil), "query.RetrieveRentalsHistory")
	proto.RegisterType((*RetrieveRentalHistory)(nil), "query.RetrieveRentalHistory")
	proto.RegisterType((*RetrieveCartItems)(nil), "query.RetrieveCartItems")
	proto.RegisterType((*RetrieveItem)(nil), "query.RetrieveItem")
}

func init() { proto.RegisterFile("queries/rental.proto", fileDescriptor_ff488d7bb5d7fae2) }

var fileDescriptor_ff488d7bb5d7fae2 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0xd2, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0x05, 0x70, 0xe2, 0x9f, 0x62, 0xa7, 0x22, 0x18, 0xaa, 0x16, 0x3d, 0x58, 0x72, 0x90, 0x5e,
	0x9a, 0x80, 0x9e, 0xc4, 0x83, 0xa0, 0x20, 0x0a, 0x9e, 0x22, 0x5e, 0xbc, 0x48, 0xda, 0x4c, 0xcd,
	0xd0, 0x6c, 0xd6, 0xce, 0xce, 0x16, 0xfa, 0xed, 0x65, 0x77, 0x1b, 0xb0, 0x07, 0xbd, 0xf5, 0xb6,
	0xbc, 0x07, 0xfb, 0x1b, 0x86, 0x81, 0xfe, 0xc2, 0x22, 0x13, 0x9a, 0x8c, 0xb1, 0x91, 0xa2, 0x4e,
	0xbf, 0x59, 0x8b, 0x8e, 0xf7, 0x5d, 0xba, 0x3a, 0xef, 0x97, 0x5a, 0x15, 0xd4, 0x98, 0x6c, 0x46,
	0xb5, 0x20, 0x87, 0x32, 0x61, 0x38, 0xcb, 0x51, 0x98, 0x70, 0x89, 0x6f, 0xa2, 0x19, 0x67, 0xac,
	0x1b, 0x79, 0x11, 0x54, 0x26, 0x8e, 0x61, 0xcf, 0x5a, 0x2a, 0x07, 0xd1, 0x30, 0x1a, 0x75, 0x73,
	0xff, 0x8e, 0x2f, 0xa0, 0x6b, 0x0d, 0xf2, 0xa7, 0x2f, 0x76, 0x7c, 0x71, 0xe0, 0x82, 0x77, 0x57,
	0x5e, 0x41, 0x27, 0xfc, 0x3d, 0xd8, 0x1d, 0x46, 0xa3, 0xde, 0xf5, 0x51, 0x1a, 0xc8, 0xf4, 0xc9,
	0xa7, 0xf9, 0xba, 0x4d, 0x16, 0x70, 0xda, 0x9a, 0xb9, 0x1f, 0xd4, 0x3c, 0x93, 0x11, 0xcd, 0xab,
	0xed, 0x91, 0xaf, 0x70, 0xb2, 0x49, 0xfe, 0x27, 0x5e, 0x42, 0x2f, 0x2c, 0xf0, 0xb7, 0x09, 0x21,
	0x72, 0x6a, 0x52, 0xc3, 0x71, 0xfb, 0xdb, 0x63, 0xc1, 0xdb, 0x5e, 0xd7, 0x3d, 0x1c, 0xb6, 0x9a,
	0x93, 0xfe, 0x82, 0x48, 0x50, 0x6d, 0x40, 0x2e, 0x70, 0xd0, 0xc3, 0xdd, 0xc7, 0xed, 0x17, 0x49,
	0x65, 0x27, 0xe9, 0x54, 0xab, 0x8c, 0xea, 0xaa, 0x50, 0xaa, 0x2a, 0xcb, 0x6c, 0x6e, 0xcb, 0x62,
	0x4e, 0x63, 0x37, 0xd0, 0xd8, 0x20, 0x2f, 0x69, 0x8a, 0x19, 0x36, 0x42, 0xe2, 0x4e, 0x68, 0x7d,
	0x4a, 0x93, 0x8e, 0xbf, 0x93, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xdc, 0x80, 0x3d,
	0x5c, 0x02, 0x00, 0x00,
}
