// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/kudaki_event.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	kudaki_event "github.com/ilhammhdd/kudaki-user-service/entities/domains/kudaki_event"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventAdProposed struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus  `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEventAds       *kudaki_event.EventAd `protobuf:"bytes,3,opt,name=kudaki_event_ads,json=kudakiEventAds,proto3" json:"kudaki_event_ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventAdProposed) Reset()         { *m = EventAdProposed{} }
func (m *EventAdProposed) String() string { return proto.CompactTextString(m) }
func (*EventAdProposed) ProtoMessage()    {}
func (*EventAdProposed) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{0}
}

func (m *EventAdProposed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAdProposed.Unmarshal(m, b)
}
func (m *EventAdProposed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAdProposed.Marshal(b, m, deterministic)
}
func (m *EventAdProposed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAdProposed.Merge(m, src)
}
func (m *EventAdProposed) XXX_Size() int {
	return xxx_messageInfo_EventAdProposed.Size(m)
}
func (m *EventAdProposed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAdProposed.DiscardUnknown(m)
}

var xxx_messageInfo_EventAdProposed proto.InternalMessageInfo

func (m *EventAdProposed) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventAdProposed) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *EventAdProposed) GetKudakiEventAds() *kudaki_event.EventAd {
	if m != nil {
		return m.KudakiEventAds
	}
	return nil
}

type OrganizerAndEventVerified struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus  `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEventAds       *kudaki_event.EventAd `protobuf:"bytes,3,opt,name=kudaki_event_ads,json=kudakiEventAds,proto3" json:"kudaki_event_ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OrganizerAndEventVerified) Reset()         { *m = OrganizerAndEventVerified{} }
func (m *OrganizerAndEventVerified) String() string { return proto.CompactTextString(m) }
func (*OrganizerAndEventVerified) ProtoMessage()    {}
func (*OrganizerAndEventVerified) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{1}
}

func (m *OrganizerAndEventVerified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizerAndEventVerified.Unmarshal(m, b)
}
func (m *OrganizerAndEventVerified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizerAndEventVerified.Marshal(b, m, deterministic)
}
func (m *OrganizerAndEventVerified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizerAndEventVerified.Merge(m, src)
}
func (m *OrganizerAndEventVerified) XXX_Size() int {
	return xxx_messageInfo_OrganizerAndEventVerified.Size(m)
}
func (m *OrganizerAndEventVerified) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizerAndEventVerified.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizerAndEventVerified proto.InternalMessageInfo

func (m *OrganizerAndEventVerified) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OrganizerAndEventVerified) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrganizerAndEventVerified) GetKudakiEventAds() *kudaki_event.EventAd {
	if m != nil {
		return m.KudakiEventAds
	}
	return nil
}

type OrganizersRetrieved struct {
	Uuid                 string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus      `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter           `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Organizers           []*kudaki_event.Organizer `protobuf:"bytes,4,rep,name=organizers,proto3" json:"organizers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OrganizersRetrieved) Reset()         { *m = OrganizersRetrieved{} }
func (m *OrganizersRetrieved) String() string { return proto.CompactTextString(m) }
func (*OrganizersRetrieved) ProtoMessage()    {}
func (*OrganizersRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{2}
}

func (m *OrganizersRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizersRetrieved.Unmarshal(m, b)
}
func (m *OrganizersRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizersRetrieved.Marshal(b, m, deterministic)
}
func (m *OrganizersRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizersRetrieved.Merge(m, src)
}
func (m *OrganizersRetrieved) XXX_Size() int {
	return xxx_messageInfo_OrganizersRetrieved.Size(m)
}
func (m *OrganizersRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizersRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizersRetrieved proto.InternalMessageInfo

func (m *OrganizersRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OrganizersRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrganizersRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *OrganizersRetrieved) GetOrganizers() []*kudaki_event.Organizer {
	if m != nil {
		return m.Organizers
	}
	return nil
}

type OrganizerRetrieved struct {
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus    `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Organizer            *kudaki_event.Organizer `protobuf:"bytes,3,opt,name=organizer,proto3" json:"organizer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OrganizerRetrieved) Reset()         { *m = OrganizerRetrieved{} }
func (m *OrganizerRetrieved) String() string { return proto.CompactTextString(m) }
func (*OrganizerRetrieved) ProtoMessage()    {}
func (*OrganizerRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{3}
}

func (m *OrganizerRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizerRetrieved.Unmarshal(m, b)
}
func (m *OrganizerRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizerRetrieved.Marshal(b, m, deterministic)
}
func (m *OrganizerRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizerRetrieved.Merge(m, src)
}
func (m *OrganizerRetrieved) XXX_Size() int {
	return xxx_messageInfo_OrganizerRetrieved.Size(m)
}
func (m *OrganizerRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizerRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizerRetrieved proto.InternalMessageInfo

func (m *OrganizerRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OrganizerRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrganizerRetrieved) GetOrganizer() *kudaki_event.Organizer {
	if m != nil {
		return m.Organizer
	}
	return nil
}

type OrganizerSearched struct {
	Uuid                 string                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus      `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Key                  string                    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Organizers           []*kudaki_event.Organizer `protobuf:"bytes,4,rep,name=organizers,proto3" json:"organizers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OrganizerSearched) Reset()         { *m = OrganizerSearched{} }
func (m *OrganizerSearched) String() string { return proto.CompactTextString(m) }
func (*OrganizerSearched) ProtoMessage()    {}
func (*OrganizerSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{4}
}

func (m *OrganizerSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizerSearched.Unmarshal(m, b)
}
func (m *OrganizerSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizerSearched.Marshal(b, m, deterministic)
}
func (m *OrganizerSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizerSearched.Merge(m, src)
}
func (m *OrganizerSearched) XXX_Size() int {
	return xxx_messageInfo_OrganizerSearched.Size(m)
}
func (m *OrganizerSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizerSearched.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizerSearched proto.InternalMessageInfo

func (m *OrganizerSearched) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OrganizerSearched) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrganizerSearched) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *OrganizerSearched) GetOrganizers() []*kudaki_event.Organizer {
	if m != nil {
		return m.Organizers
	}
	return nil
}

type EventAdPublished struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus  `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEventAds       *kudaki_event.EventAd `protobuf:"bytes,3,opt,name=kudaki_event_ads,json=kudakiEventAds,proto3" json:"kudaki_event_ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventAdPublished) Reset()         { *m = EventAdPublished{} }
func (m *EventAdPublished) String() string { return proto.CompactTextString(m) }
func (*EventAdPublished) ProtoMessage()    {}
func (*EventAdPublished) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{5}
}

func (m *EventAdPublished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAdPublished.Unmarshal(m, b)
}
func (m *EventAdPublished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAdPublished.Marshal(b, m, deterministic)
}
func (m *EventAdPublished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAdPublished.Merge(m, src)
}
func (m *EventAdPublished) XXX_Size() int {
	return xxx_messageInfo_EventAdPublished.Size(m)
}
func (m *EventAdPublished) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAdPublished.DiscardUnknown(m)
}

var xxx_messageInfo_EventAdPublished proto.InternalMessageInfo

func (m *EventAdPublished) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventAdPublished) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *EventAdPublished) GetKudakiEventAds() *kudaki_event.EventAd {
	if m != nil {
		return m.KudakiEventAds
	}
	return nil
}

type RegisteredToEvent struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus  `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEventAds       *kudaki_event.EventAd `protobuf:"bytes,3,opt,name=kudaki_event_ads,json=kudakiEventAds,proto3" json:"kudaki_event_ads,omitempty"`
	User                 *user.User            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisteredToEvent) Reset()         { *m = RegisteredToEvent{} }
func (m *RegisteredToEvent) String() string { return proto.CompactTextString(m) }
func (*RegisteredToEvent) ProtoMessage()    {}
func (*RegisteredToEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{6}
}

func (m *RegisteredToEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredToEvent.Unmarshal(m, b)
}
func (m *RegisteredToEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredToEvent.Marshal(b, m, deterministic)
}
func (m *RegisteredToEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredToEvent.Merge(m, src)
}
func (m *RegisteredToEvent) XXX_Size() int {
	return xxx_messageInfo_RegisteredToEvent.Size(m)
}
func (m *RegisteredToEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredToEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredToEvent proto.InternalMessageInfo

func (m *RegisteredToEvent) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisteredToEvent) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RegisteredToEvent) GetKudakiEventAds() *kudaki_event.EventAd {
	if m != nil {
		return m.KudakiEventAds
	}
	return nil
}

func (m *RegisteredToEvent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type EventAdsRetrieved struct {
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus    `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter         `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	EventAds             []*kudaki_event.EventAd `protobuf:"bytes,4,rep,name=event_ads,json=eventAds,proto3" json:"event_ads,omitempty"`
	User                 *user.User              `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EventAdsRetrieved) Reset()         { *m = EventAdsRetrieved{} }
func (m *EventAdsRetrieved) String() string { return proto.CompactTextString(m) }
func (*EventAdsRetrieved) ProtoMessage()    {}
func (*EventAdsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{7}
}

func (m *EventAdsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAdsRetrieved.Unmarshal(m, b)
}
func (m *EventAdsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAdsRetrieved.Marshal(b, m, deterministic)
}
func (m *EventAdsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAdsRetrieved.Merge(m, src)
}
func (m *EventAdsRetrieved) XXX_Size() int {
	return xxx_messageInfo_EventAdsRetrieved.Size(m)
}
func (m *EventAdsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAdsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_EventAdsRetrieved proto.InternalMessageInfo

func (m *EventAdsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventAdsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *EventAdsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *EventAdsRetrieved) GetEventAds() []*kudaki_event.EventAd {
	if m != nil {
		return m.EventAds
	}
	return nil
}

func (m *EventAdsRetrieved) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type EventAdRetrieved struct {
	Uuid                 string                `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus  `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	EventAd              *kudaki_event.EventAd `protobuf:"bytes,3,opt,name=event_ad,json=eventAd,proto3" json:"event_ad,omitempty"`
	User                 *user.User            `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventAdRetrieved) Reset()         { *m = EventAdRetrieved{} }
func (m *EventAdRetrieved) String() string { return proto.CompactTextString(m) }
func (*EventAdRetrieved) ProtoMessage()    {}
func (*EventAdRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{8}
}

func (m *EventAdRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAdRetrieved.Unmarshal(m, b)
}
func (m *EventAdRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAdRetrieved.Marshal(b, m, deterministic)
}
func (m *EventAdRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAdRetrieved.Merge(m, src)
}
func (m *EventAdRetrieved) XXX_Size() int {
	return xxx_messageInfo_EventAdRetrieved.Size(m)
}
func (m *EventAdRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAdRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_EventAdRetrieved proto.InternalMessageInfo

func (m *EventAdRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventAdRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *EventAdRetrieved) GetEventAd() *kudaki_event.EventAd {
	if m != nil {
		return m.EventAd
	}
	return nil
}

func (m *EventAdRetrieved) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type EventAdSearched struct {
	Uuid                 string                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus    `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Key                  string                  `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	EventAds             []*kudaki_event.EventAd `protobuf:"bytes,4,rep,name=event_ads,json=eventAds,proto3" json:"event_ads,omitempty"`
	User                 *user.User              `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EventAdSearched) Reset()         { *m = EventAdSearched{} }
func (m *EventAdSearched) String() string { return proto.CompactTextString(m) }
func (*EventAdSearched) ProtoMessage()    {}
func (*EventAdSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{9}
}

func (m *EventAdSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAdSearched.Unmarshal(m, b)
}
func (m *EventAdSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAdSearched.Marshal(b, m, deterministic)
}
func (m *EventAdSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAdSearched.Merge(m, src)
}
func (m *EventAdSearched) XXX_Size() int {
	return xxx_messageInfo_EventAdSearched.Size(m)
}
func (m *EventAdSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAdSearched.DiscardUnknown(m)
}

var xxx_messageInfo_EventAdSearched proto.InternalMessageInfo

func (m *EventAdSearched) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EventAdSearched) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *EventAdSearched) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EventAdSearched) GetEventAds() []*kudaki_event.EventAd {
	if m != nil {
		return m.EventAds
	}
	return nil
}

func (m *EventAdSearched) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*EventAdProposed)(nil), "event.EventAdProposed")
	proto.RegisterType((*OrganizerAndEventVerified)(nil), "event.OrganizerAndEventVerified")
	proto.RegisterType((*OrganizersRetrieved)(nil), "event.OrganizersRetrieved")
	proto.RegisterType((*OrganizerRetrieved)(nil), "event.OrganizerRetrieved")
	proto.RegisterType((*OrganizerSearched)(nil), "event.OrganizerSearched")
	proto.RegisterType((*EventAdPublished)(nil), "event.EventAdPublished")
	proto.RegisterType((*RegisteredToEvent)(nil), "event.RegisteredToEvent")
	proto.RegisterType((*EventAdsRetrieved)(nil), "event.EventAdsRetrieved")
	proto.RegisterType((*EventAdRetrieved)(nil), "event.EventAdRetrieved")
	proto.RegisterType((*EventAdSearched)(nil), "event.EventAdSearched")
}

func init() { proto.RegisterFile("events/kudaki_event.proto", fileDescriptor_fa36ed941739bd5b) }

var fileDescriptor_fa36ed941739bd5b = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x66, 0x4c, 0x5a, 0x9b, 0x13, 0xa9, 0xc9, 0x56, 0x70, 0x5b, 0x44, 0xc2, 0xfa, 0x43, 0x6e,
	0x9a, 0x40, 0x05, 0xff, 0x10, 0xa1, 0x82, 0xbd, 0x55, 0xa6, 0xea, 0x85, 0x37, 0x61, 0x93, 0x39,
	0xcd, 0x0e, 0x49, 0x76, 0xcb, 0xcc, 0x6c, 0x40, 0x1f, 0xc6, 0x3b, 0xbd, 0x15, 0x5f, 0xc0, 0x7b,
	0x6f, 0x04, 0x1f, 0xc3, 0xb7, 0x90, 0x3d, 0x33, 0xb3, 0xdb, 0x6a, 0xa9, 0x05, 0x1b, 0x9b, 0x9b,
	0x65, 0xcf, 0xf9, 0xce, 0x37, 0xf9, 0xbe, 0x39, 0x67, 0x76, 0x02, 0x9b, 0x38, 0xc7, 0xd4, 0xe8,
	0xfe, 0x24, 0x17, 0xf1, 0x44, 0x0e, 0x28, 0xea, 0x1d, 0xaa, 0xcc, 0x64, 0xc1, 0x0a, 0x05, 0x5b,
	0xb7, 0x44, 0x36, 0x8b, 0x65, 0x7a, 0xbc, 0xa4, 0x4f, 0xcf, 0x41, 0x2c, 0x6c, 0xed, 0xd6, 0xed,
	0x13, 0x8b, 0x32, 0x35, 0x8e, 0x53, 0xf9, 0x1e, 0x95, 0xab, 0xba, 0xee, 0xab, 0x72, 0x8d, 0x8a,
	0x1e, 0x0e, 0xb8, 0xe6, 0x81, 0x03, 0x39, 0x35, 0x7f, 0x66, 0xb5, 0x89, 0x4d, 0xae, 0x6d, 0x36,
	0xfa, 0xc8, 0xe0, 0xea, 0xf3, 0x62, 0xf9, 0x5d, 0xf1, 0x52, 0x65, 0x87, 0x99, 0x46, 0x11, 0x04,
	0x50, 0xcf, 0x73, 0x29, 0x42, 0xd6, 0x61, 0xdd, 0x06, 0xa7, 0xf7, 0xe0, 0x3e, 0x5c, 0xb1, 0x22,
	0x2d, 0x3b, 0xbc, 0xd4, 0x61, 0xdd, 0xe6, 0xce, 0x46, 0xcf, 0x2e, 0xda, 0xa3, 0x25, 0xf6, 0x09,
	0xe2, 0x4d, 0xac, 0x82, 0x60, 0x0f, 0x5a, 0x47, 0x4d, 0x0c, 0x62, 0xa1, 0xc3, 0x1a, 0x71, 0x6f,
	0x78, 0xee, 0xb1, 0xcd, 0x72, 0x5a, 0xf8, 0xba, 0xcd, 0xba, 0x50, 0x47, 0x9f, 0x19, 0x6c, 0xbe,
	0xf0, 0x1b, 0xb0, 0x9b, 0x0a, 0x02, 0xde, 0xa0, 0x92, 0x07, 0x72, 0x49, 0x15, 0x7f, 0x63, 0xb0,
	0x51, 0x2a, 0xd6, 0x1c, 0x8d, 0x92, 0x38, 0x3f, 0x67, 0xad, 0x77, 0x61, 0xd5, 0xf6, 0xd8, 0x29,
	0x5c, 0xf7, 0x8c, 0x3d, 0xca, 0x72, 0x87, 0x06, 0x4f, 0x01, 0xca, 0xe9, 0xd1, 0x61, 0xbd, 0x53,
	0xeb, 0x36, 0x77, 0x6e, 0x9e, 0xe8, 0xa6, 0x54, 0xcc, 0x8f, 0x30, 0xa2, 0x0f, 0x0c, 0x82, 0x0a,
	0x59, 0x88, 0x95, 0x27, 0xd0, 0x28, 0x7f, 0xd0, 0xb9, 0xf9, 0x9b, 0xc2, 0x8a, 0x10, 0x7d, 0x61,
	0xd0, 0x2e, 0x81, 0x7d, 0x8c, 0xd5, 0x28, 0x39, 0x67, 0x7d, 0x2d, 0xa8, 0x4d, 0xf0, 0x1d, 0x29,
	0x6b, 0xf0, 0xe2, 0xf5, 0x9f, 0x37, 0xf5, 0x13, 0x83, 0x96, 0x3f, 0x7a, 0xf9, 0x70, 0x2a, 0x75,
	0xb2, 0xa4, 0x93, 0xfc, 0x9d, 0x41, 0x9b, 0xe3, 0x58, 0x6a, 0x83, 0x0a, 0xc5, 0xab, 0x8c, 0x80,
	0x65, 0x54, 0x1a, 0xdc, 0x81, 0x7a, 0xf1, 0x1d, 0x0c, 0xeb, 0xc4, 0x6d, 0x7b, 0x2e, 0x7d, 0x1b,
	0x5f, 0x6b, 0x54, 0x9c, 0xe0, 0xe8, 0x27, 0x83, 0xb6, 0xe7, 0x5c, 0xec, 0xc1, 0x7c, 0x04, 0x8d,
	0xca, 0xb1, 0x1d, 0xa1, 0xd3, 0x1d, 0xaf, 0xe1, 0xef, 0x5e, 0x57, 0x4e, 0xf7, 0xfa, 0xb5, 0x9a,
	0xb2, 0xc5, 0x58, 0x7d, 0x00, 0x6b, 0xde, 0xc2, 0x99, 0x7a, 0x76, 0xd9, 0x39, 0x38, 0x6b, 0xb3,
	0x7e, 0x54, 0x37, 0xd4, 0x7f, 0x3a, 0xd8, 0x0b, 0x6f, 0xca, 0xb3, 0xc7, 0x6f, 0x1f, 0x8e, 0xa5,
	0x49, 0xf2, 0x61, 0x6f, 0x94, 0xcd, 0xfa, 0x72, 0x9a, 0xc4, 0xb3, 0x59, 0x22, 0x84, 0xbb, 0xef,
	0xb7, 0x8b, 0x9a, 0x6d, 0x8d, 0x6a, 0x2e, 0x47, 0xd8, 0xc7, 0xd4, 0x48, 0x23, 0x51, 0xdb, 0x3f,
	0x09, 0x7a, 0xb8, 0x4a, 0x17, 0xf7, 0xbd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x3e, 0x2b,
	0x47, 0x6c, 0x08, 0x00, 0x00,
}
