// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/mountain.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	mountain "github.com/ilhammhdd/kudaki-user-service/entities/domains/mountain"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MountainAdded struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Mountain             *mountain.Mountain   `protobuf:"bytes,3,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainAdded) Reset()         { *m = MountainAdded{} }
func (m *MountainAdded) String() string { return proto.CompactTextString(m) }
func (*MountainAdded) ProtoMessage()    {}
func (*MountainAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{0}
}

func (m *MountainAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainAdded.Unmarshal(m, b)
}
func (m *MountainAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainAdded.Marshal(b, m, deterministic)
}
func (m *MountainAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainAdded.Merge(m, src)
}
func (m *MountainAdded) XXX_Size() int {
	return xxx_messageInfo_MountainAdded.Size(m)
}
func (m *MountainAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainAdded.DiscardUnknown(m)
}

var xxx_messageInfo_MountainAdded proto.InternalMessageInfo

func (m *MountainAdded) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainAdded) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainAdded) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type MountainEdited struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Mountain             *mountain.Mountain   `protobuf:"bytes,3,opt,name=mountain,proto3" json:"mountain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainEdited) Reset()         { *m = MountainEdited{} }
func (m *MountainEdited) String() string { return proto.CompactTextString(m) }
func (*MountainEdited) ProtoMessage()    {}
func (*MountainEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{1}
}

func (m *MountainEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainEdited.Unmarshal(m, b)
}
func (m *MountainEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainEdited.Marshal(b, m, deterministic)
}
func (m *MountainEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainEdited.Merge(m, src)
}
func (m *MountainEdited) XXX_Size() int {
	return xxx_messageInfo_MountainEdited.Size(m)
}
func (m *MountainEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainEdited.DiscardUnknown(m)
}

var xxx_messageInfo_MountainEdited proto.InternalMessageInfo

func (m *MountainEdited) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainEdited) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainEdited) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

type MountainsRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Mountains            []*mountain.Mountain `protobuf:"bytes,4,rep,name=mountains,proto3" json:"mountains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainsRetrieved) Reset()         { *m = MountainsRetrieved{} }
func (m *MountainsRetrieved) String() string { return proto.CompactTextString(m) }
func (*MountainsRetrieved) ProtoMessage()    {}
func (*MountainsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{2}
}

func (m *MountainsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainsRetrieved.Unmarshal(m, b)
}
func (m *MountainsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainsRetrieved.Marshal(b, m, deterministic)
}
func (m *MountainsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainsRetrieved.Merge(m, src)
}
func (m *MountainsRetrieved) XXX_Size() int {
	return xxx_messageInfo_MountainsRetrieved.Size(m)
}
func (m *MountainsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_MountainsRetrieved proto.InternalMessageInfo

func (m *MountainsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *MountainsRetrieved) GetMountains() []*mountain.Mountain {
	if m != nil {
		return m.Mountains
	}
	return nil
}

type MountainRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Mountains            *mountain.Mountain   `protobuf:"bytes,3,opt,name=mountains,proto3" json:"mountains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainRetrieved) Reset()         { *m = MountainRetrieved{} }
func (m *MountainRetrieved) String() string { return proto.CompactTextString(m) }
func (*MountainRetrieved) ProtoMessage()    {}
func (*MountainRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{3}
}

func (m *MountainRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainRetrieved.Unmarshal(m, b)
}
func (m *MountainRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainRetrieved.Marshal(b, m, deterministic)
}
func (m *MountainRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainRetrieved.Merge(m, src)
}
func (m *MountainRetrieved) XXX_Size() int {
	return xxx_messageInfo_MountainRetrieved.Size(m)
}
func (m *MountainRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_MountainRetrieved proto.InternalMessageInfo

func (m *MountainRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainRetrieved) GetMountains() *mountain.Mountain {
	if m != nil {
		return m.Mountains
	}
	return nil
}

type MountainsSearched struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Key                  string               `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Results              []*mountain.Mountain `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainsSearched) Reset()         { *m = MountainsSearched{} }
func (m *MountainsSearched) String() string { return proto.CompactTextString(m) }
func (*MountainsSearched) ProtoMessage()    {}
func (*MountainsSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{4}
}

func (m *MountainsSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainsSearched.Unmarshal(m, b)
}
func (m *MountainsSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainsSearched.Marshal(b, m, deterministic)
}
func (m *MountainsSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainsSearched.Merge(m, src)
}
func (m *MountainsSearched) XXX_Size() int {
	return xxx_messageInfo_MountainsSearched.Size(m)
}
func (m *MountainsSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainsSearched.DiscardUnknown(m)
}

var xxx_messageInfo_MountainsSearched proto.InternalMessageInfo

func (m *MountainsSearched) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainsSearched) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainsSearched) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MountainsSearched) GetResults() []*mountain.Mountain {
	if m != nil {
		return m.Results
	}
	return nil
}

type MountainReviewed struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Review               *mountain.Review     `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainReviewed) Reset()         { *m = MountainReviewed{} }
func (m *MountainReviewed) String() string { return proto.CompactTextString(m) }
func (*MountainReviewed) ProtoMessage()    {}
func (*MountainReviewed) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{5}
}

func (m *MountainReviewed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainReviewed.Unmarshal(m, b)
}
func (m *MountainReviewed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainReviewed.Marshal(b, m, deterministic)
}
func (m *MountainReviewed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainReviewed.Merge(m, src)
}
func (m *MountainReviewed) XXX_Size() int {
	return xxx_messageInfo_MountainReviewed.Size(m)
}
func (m *MountainReviewed) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainReviewed.DiscardUnknown(m)
}

var xxx_messageInfo_MountainReviewed proto.InternalMessageInfo

func (m *MountainReviewed) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainReviewed) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainReviewed) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type MountainReviewEdited struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Review               *mountain.Review     `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainReviewEdited) Reset()         { *m = MountainReviewEdited{} }
func (m *MountainReviewEdited) String() string { return proto.CompactTextString(m) }
func (*MountainReviewEdited) ProtoMessage()    {}
func (*MountainReviewEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{6}
}

func (m *MountainReviewEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainReviewEdited.Unmarshal(m, b)
}
func (m *MountainReviewEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainReviewEdited.Marshal(b, m, deterministic)
}
func (m *MountainReviewEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainReviewEdited.Merge(m, src)
}
func (m *MountainReviewEdited) XXX_Size() int {
	return xxx_messageInfo_MountainReviewEdited.Size(m)
}
func (m *MountainReviewEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainReviewEdited.DiscardUnknown(m)
}

var xxx_messageInfo_MountainReviewEdited proto.InternalMessageInfo

func (m *MountainReviewEdited) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainReviewEdited) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainReviewEdited) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type MountainReviewDeleted struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Review               *mountain.Review     `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainReviewDeleted) Reset()         { *m = MountainReviewDeleted{} }
func (m *MountainReviewDeleted) String() string { return proto.CompactTextString(m) }
func (*MountainReviewDeleted) ProtoMessage()    {}
func (*MountainReviewDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{7}
}

func (m *MountainReviewDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainReviewDeleted.Unmarshal(m, b)
}
func (m *MountainReviewDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainReviewDeleted.Marshal(b, m, deterministic)
}
func (m *MountainReviewDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainReviewDeleted.Merge(m, src)
}
func (m *MountainReviewDeleted) XXX_Size() int {
	return xxx_messageInfo_MountainReviewDeleted.Size(m)
}
func (m *MountainReviewDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainReviewDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_MountainReviewDeleted proto.InternalMessageInfo

func (m *MountainReviewDeleted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainReviewDeleted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainReviewDeleted) GetReview() *mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type MountainReviewsRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Review               []*mountain.Review   `protobuf:"bytes,4,rep,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MountainReviewsRetrieved) Reset()         { *m = MountainReviewsRetrieved{} }
func (m *MountainReviewsRetrieved) String() string { return proto.CompactTextString(m) }
func (*MountainReviewsRetrieved) ProtoMessage()    {}
func (*MountainReviewsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{8}
}

func (m *MountainReviewsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountainReviewsRetrieved.Unmarshal(m, b)
}
func (m *MountainReviewsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountainReviewsRetrieved.Marshal(b, m, deterministic)
}
func (m *MountainReviewsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountainReviewsRetrieved.Merge(m, src)
}
func (m *MountainReviewsRetrieved) XXX_Size() int {
	return xxx_messageInfo_MountainReviewsRetrieved.Size(m)
}
func (m *MountainReviewsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MountainReviewsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_MountainReviewsRetrieved proto.InternalMessageInfo

func (m *MountainReviewsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MountainReviewsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *MountainReviewsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *MountainReviewsRetrieved) GetReview() []*mountain.Review {
	if m != nil {
		return m.Review
	}
	return nil
}

type RecomendedGearsRetrieved struct {
	Uuid                 string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter            `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	RecomendedGears      []*mountain.RecomendedGear `protobuf:"bytes,4,rep,name=recomended_gears,json=recomendedGears,proto3" json:"recomended_gears,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RecomendedGearsRetrieved) Reset()         { *m = RecomendedGearsRetrieved{} }
func (m *RecomendedGearsRetrieved) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearsRetrieved) ProtoMessage()    {}
func (*RecomendedGearsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{9}
}

func (m *RecomendedGearsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearsRetrieved.Unmarshal(m, b)
}
func (m *RecomendedGearsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearsRetrieved.Marshal(b, m, deterministic)
}
func (m *RecomendedGearsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearsRetrieved.Merge(m, src)
}
func (m *RecomendedGearsRetrieved) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearsRetrieved.Size(m)
}
func (m *RecomendedGearsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearsRetrieved proto.InternalMessageInfo

func (m *RecomendedGearsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RecomendedGearsRetrieved) GetRecomendedGears() []*mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGears
	}
	return nil
}

type RecomendedGearRetrieved struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGears      *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gears,json=recomendedGears,proto3" json:"recomended_gears,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearRetrieved) Reset()         { *m = RecomendedGearRetrieved{} }
func (m *RecomendedGearRetrieved) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearRetrieved) ProtoMessage()    {}
func (*RecomendedGearRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{10}
}

func (m *RecomendedGearRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearRetrieved.Unmarshal(m, b)
}
func (m *RecomendedGearRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearRetrieved.Marshal(b, m, deterministic)
}
func (m *RecomendedGearRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearRetrieved.Merge(m, src)
}
func (m *RecomendedGearRetrieved) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearRetrieved.Size(m)
}
func (m *RecomendedGearRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearRetrieved proto.InternalMessageInfo

func (m *RecomendedGearRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearRetrieved) GetRecomendedGears() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGears
	}
	return nil
}

type RecomendedGearAdded struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearAdded) Reset()         { *m = RecomendedGearAdded{} }
func (m *RecomendedGearAdded) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearAdded) ProtoMessage()    {}
func (*RecomendedGearAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{11}
}

func (m *RecomendedGearAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearAdded.Unmarshal(m, b)
}
func (m *RecomendedGearAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearAdded.Marshal(b, m, deterministic)
}
func (m *RecomendedGearAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearAdded.Merge(m, src)
}
func (m *RecomendedGearAdded) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearAdded.Size(m)
}
func (m *RecomendedGearAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearAdded.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearAdded proto.InternalMessageInfo

func (m *RecomendedGearAdded) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearAdded) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearAdded) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type RecomendedGearEdited struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearEdited) Reset()         { *m = RecomendedGearEdited{} }
func (m *RecomendedGearEdited) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearEdited) ProtoMessage()    {}
func (*RecomendedGearEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{12}
}

func (m *RecomendedGearEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearEdited.Unmarshal(m, b)
}
func (m *RecomendedGearEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearEdited.Marshal(b, m, deterministic)
}
func (m *RecomendedGearEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearEdited.Merge(m, src)
}
func (m *RecomendedGearEdited) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearEdited.Size(m)
}
func (m *RecomendedGearEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearEdited.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearEdited proto.InternalMessageInfo

func (m *RecomendedGearEdited) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearEdited) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearEdited) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type RecomendedGearDeleted struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearDeleted) Reset()         { *m = RecomendedGearDeleted{} }
func (m *RecomendedGearDeleted) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearDeleted) ProtoMessage()    {}
func (*RecomendedGearDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{13}
}

func (m *RecomendedGearDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearDeleted.Unmarshal(m, b)
}
func (m *RecomendedGearDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearDeleted.Marshal(b, m, deterministic)
}
func (m *RecomendedGearDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearDeleted.Merge(m, src)
}
func (m *RecomendedGearDeleted) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearDeleted.Size(m)
}
func (m *RecomendedGearDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearDeleted proto.InternalMessageInfo

func (m *RecomendedGearDeleted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearDeleted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearDeleted) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type RecomendedGearUpVoted struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearUpVoted) Reset()         { *m = RecomendedGearUpVoted{} }
func (m *RecomendedGearUpVoted) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearUpVoted) ProtoMessage()    {}
func (*RecomendedGearUpVoted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{14}
}

func (m *RecomendedGearUpVoted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearUpVoted.Unmarshal(m, b)
}
func (m *RecomendedGearUpVoted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearUpVoted.Marshal(b, m, deterministic)
}
func (m *RecomendedGearUpVoted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearUpVoted.Merge(m, src)
}
func (m *RecomendedGearUpVoted) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearUpVoted.Size(m)
}
func (m *RecomendedGearUpVoted) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearUpVoted.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearUpVoted proto.InternalMessageInfo

func (m *RecomendedGearUpVoted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearUpVoted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearUpVoted) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type RecomendedGearDownVoted struct {
	Uuid                 string                   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RecomendedGear       *mountain.RecomendedGear `protobuf:"bytes,3,opt,name=recomended_gear,json=recomendedGear,proto3" json:"recomended_gear,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecomendedGearDownVoted) Reset()         { *m = RecomendedGearDownVoted{} }
func (m *RecomendedGearDownVoted) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearDownVoted) ProtoMessage()    {}
func (*RecomendedGearDownVoted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{15}
}

func (m *RecomendedGearDownVoted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearDownVoted.Unmarshal(m, b)
}
func (m *RecomendedGearDownVoted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearDownVoted.Marshal(b, m, deterministic)
}
func (m *RecomendedGearDownVoted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearDownVoted.Merge(m, src)
}
func (m *RecomendedGearDownVoted) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearDownVoted.Size(m)
}
func (m *RecomendedGearDownVoted) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearDownVoted.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearDownVoted proto.InternalMessageInfo

func (m *RecomendedGearDownVoted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearDownVoted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearDownVoted) GetRecomendedGear() *mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGear
	}
	return nil
}

type RecomendedGearSearched struct {
	Uuid                 string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Key                  string                     `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Mountain             *mountain.Mountain         `protobuf:"bytes,4,opt,name=mountain,proto3" json:"mountain,omitempty"`
	RecomendedGears      []*mountain.RecomendedGear `protobuf:"bytes,5,rep,name=recomended_gears,json=recomendedGears,proto3" json:"recomended_gears,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RecomendedGearSearched) Reset()         { *m = RecomendedGearSearched{} }
func (m *RecomendedGearSearched) String() string { return proto.CompactTextString(m) }
func (*RecomendedGearSearched) ProtoMessage()    {}
func (*RecomendedGearSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{16}
}

func (m *RecomendedGearSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecomendedGearSearched.Unmarshal(m, b)
}
func (m *RecomendedGearSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecomendedGearSearched.Marshal(b, m, deterministic)
}
func (m *RecomendedGearSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecomendedGearSearched.Merge(m, src)
}
func (m *RecomendedGearSearched) XXX_Size() int {
	return xxx_messageInfo_RecomendedGearSearched.Size(m)
}
func (m *RecomendedGearSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_RecomendedGearSearched.DiscardUnknown(m)
}

var xxx_messageInfo_RecomendedGearSearched proto.InternalMessageInfo

func (m *RecomendedGearSearched) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RecomendedGearSearched) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RecomendedGearSearched) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RecomendedGearSearched) GetMountain() *mountain.Mountain {
	if m != nil {
		return m.Mountain
	}
	return nil
}

func (m *RecomendedGearSearched) GetRecomendedGears() []*mountain.RecomendedGear {
	if m != nil {
		return m.RecomendedGears
	}
	return nil
}

type TripPlanned struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Trip                 *mountain.Trip       `protobuf:"bytes,3,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TripPlanned) Reset()         { *m = TripPlanned{} }
func (m *TripPlanned) String() string { return proto.CompactTextString(m) }
func (*TripPlanned) ProtoMessage()    {}
func (*TripPlanned) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{17}
}

func (m *TripPlanned) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripPlanned.Unmarshal(m, b)
}
func (m *TripPlanned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripPlanned.Marshal(b, m, deterministic)
}
func (m *TripPlanned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripPlanned.Merge(m, src)
}
func (m *TripPlanned) XXX_Size() int {
	return xxx_messageInfo_TripPlanned.Size(m)
}
func (m *TripPlanned) XXX_DiscardUnknown() {
	xxx_messageInfo_TripPlanned.DiscardUnknown(m)
}

var xxx_messageInfo_TripPlanned proto.InternalMessageInfo

func (m *TripPlanned) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TripPlanned) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TripPlanned) GetTrip() *mountain.Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

type TripCancelled struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Trip                 *mountain.Trip       `protobuf:"bytes,3,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TripCancelled) Reset()         { *m = TripCancelled{} }
func (m *TripCancelled) String() string { return proto.CompactTextString(m) }
func (*TripCancelled) ProtoMessage()    {}
func (*TripCancelled) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{18}
}

func (m *TripCancelled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripCancelled.Unmarshal(m, b)
}
func (m *TripCancelled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripCancelled.Marshal(b, m, deterministic)
}
func (m *TripCancelled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripCancelled.Merge(m, src)
}
func (m *TripCancelled) XXX_Size() int {
	return xxx_messageInfo_TripCancelled.Size(m)
}
func (m *TripCancelled) XXX_DiscardUnknown() {
	xxx_messageInfo_TripCancelled.DiscardUnknown(m)
}

var xxx_messageInfo_TripCancelled proto.InternalMessageInfo

func (m *TripCancelled) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TripCancelled) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TripCancelled) GetTrip() *mountain.Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

type TripsRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Trip                 []*mountain.Trip     `protobuf:"bytes,4,rep,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TripsRetrieved) Reset()         { *m = TripsRetrieved{} }
func (m *TripsRetrieved) String() string { return proto.CompactTextString(m) }
func (*TripsRetrieved) ProtoMessage()    {}
func (*TripsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b5343a5180c70, []int{19}
}

func (m *TripsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripsRetrieved.Unmarshal(m, b)
}
func (m *TripsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripsRetrieved.Marshal(b, m, deterministic)
}
func (m *TripsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripsRetrieved.Merge(m, src)
}
func (m *TripsRetrieved) XXX_Size() int {
	return xxx_messageInfo_TripsRetrieved.Size(m)
}
func (m *TripsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_TripsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_TripsRetrieved proto.InternalMessageInfo

func (m *TripsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TripsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TripsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *TripsRetrieved) GetTrip() []*mountain.Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

func init() {
	proto.RegisterType((*MountainAdded)(nil), "event.MountainAdded")
	proto.RegisterType((*MountainEdited)(nil), "event.MountainEdited")
	proto.RegisterType((*MountainsRetrieved)(nil), "event.MountainsRetrieved")
	proto.RegisterType((*MountainRetrieved)(nil), "event.MountainRetrieved")
	proto.RegisterType((*MountainsSearched)(nil), "event.MountainsSearched")
	proto.RegisterType((*MountainReviewed)(nil), "event.MountainReviewed")
	proto.RegisterType((*MountainReviewEdited)(nil), "event.MountainReviewEdited")
	proto.RegisterType((*MountainReviewDeleted)(nil), "event.MountainReviewDeleted")
	proto.RegisterType((*MountainReviewsRetrieved)(nil), "event.MountainReviewsRetrieved")
	proto.RegisterType((*RecomendedGearsRetrieved)(nil), "event.RecomendedGearsRetrieved")
	proto.RegisterType((*RecomendedGearRetrieved)(nil), "event.RecomendedGearRetrieved")
	proto.RegisterType((*RecomendedGearAdded)(nil), "event.RecomendedGearAdded")
	proto.RegisterType((*RecomendedGearEdited)(nil), "event.RecomendedGearEdited")
	proto.RegisterType((*RecomendedGearDeleted)(nil), "event.RecomendedGearDeleted")
	proto.RegisterType((*RecomendedGearUpVoted)(nil), "event.RecomendedGearUpVoted")
	proto.RegisterType((*RecomendedGearDownVoted)(nil), "event.RecomendedGearDownVoted")
	proto.RegisterType((*RecomendedGearSearched)(nil), "event.RecomendedGearSearched")
	proto.RegisterType((*TripPlanned)(nil), "event.TripPlanned")
	proto.RegisterType((*TripCancelled)(nil), "event.TripCancelled")
	proto.RegisterType((*TripsRetrieved)(nil), "event.TripsRetrieved")
}

func init() { proto.RegisterFile("events/mountain.proto", fileDescriptor_6f3b5343a5180c70) }

var fileDescriptor_6f3b5343a5180c70 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x35, 0x34, 0x0d, 0xe4, 0x84, 0xa6, 0xc1, 0x4d, 0xa8, 0x29, 0x42, 0x8d, 0xbc, 0xa8,
	0xca, 0xa2, 0xb1, 0x44, 0xc5, 0x45, 0xec, 0x80, 0x16, 0x10, 0x12, 0x12, 0x72, 0x81, 0x05, 0x9b,
	0xca, 0xcd, 0x1c, 0x9a, 0x51, 0x7c, 0x89, 0xc6, 0xe3, 0x54, 0xec, 0x11, 0x5b, 0x24, 0x60, 0xc1,
	0x13, 0xb0, 0x01, 0x54, 0xf1, 0x04, 0x88, 0xd7, 0xe0, 0x4d, 0xd8, 0x21, 0x5f, 0x26, 0xc9, 0x24,
	0x51, 0x9b, 0x22, 0x9b, 0x64, 0xe7, 0x39, 0xe7, 0x1f, 0xcf, 0xf7, 0x8f, 0x7d, 0xe6, 0x02, 0x75,
	0xec, 0xa1, 0x27, 0x02, 0xd3, 0xf5, 0x43, 0x4f, 0xd8, 0xcc, 0x6b, 0x76, 0xb9, 0x2f, 0x7c, 0x6d,
	0x31, 0x0e, 0xaf, 0xad, 0x53, 0xdf, 0xb5, 0x99, 0x37, 0x48, 0x8f, 0xe8, 0xd6, 0x36, 0xc6, 0x04,
	0x1c, 0x5b, 0xbe, 0x8b, 0x1e, 0x45, 0xba, 0x7f, 0x88, 0x36, 0x4f, 0x75, 0xd7, 0x26, 0xe8, 0x7a,
	0x0c, 0x8f, 0xd2, 0xf4, 0xd5, 0xb1, 0xb4, 0xe0, 0xac, 0x9b, 0x26, 0x6b, 0x32, 0xf9, 0x9a, 0x39,
	0x02, 0xf9, 0x68, 0x34, 0x10, 0xb6, 0x08, 0x83, 0x24, 0x6a, 0x7c, 0x20, 0xb0, 0xf4, 0x34, 0x7d,
	0xc7, 0x3d, 0x4a, 0x91, 0x6a, 0x1a, 0x14, 0xc2, 0x90, 0x51, 0x9d, 0x34, 0xc8, 0x66, 0xc9, 0x8a,
	0x9f, 0xb5, 0x5b, 0x70, 0x31, 0xf6, 0xb7, 0x9f, 0xf4, 0xd5, 0xcf, 0x35, 0xc8, 0x66, 0xf9, 0xc6,
	0x4a, 0x33, 0x79, 0x65, 0x73, 0x37, 0xca, 0xed, 0xc5, 0x29, 0xab, 0x8c, 0x83, 0x86, 0x76, 0x13,
	0x2e, 0x48, 0x40, 0x7d, 0x21, 0xee, 0x73, 0x45, 0xf6, 0xe9, 0xcf, 0x8b, 0x1c, 0xdd, 0xea, 0x4b,
	0x8d, 0x8f, 0x04, 0x2a, 0x32, 0xbc, 0x4b, 0x99, 0x98, 0x0f, 0xaa, 0x5f, 0x04, 0x34, 0x19, 0x0e,
	0x2c, 0x14, 0x9c, 0x61, 0x2f, 0x63, 0xb2, 0x0d, 0x28, 0x26, 0xdf, 0x2c, 0xe5, 0xaa, 0xc8, 0x1e,
	0x0f, 0xe3, 0xa8, 0x95, 0x66, 0xb5, 0xdb, 0x50, 0x92, 0x58, 0x81, 0x5e, 0x68, 0x2c, 0x9c, 0x6c,
	0x61, 0xa0, 0x35, 0x3e, 0x13, 0xb8, 0xd4, 0x8f, 0xe7, 0x62, 0x41, 0x41, 0x3b, 0x75, 0x76, 0x87,
	0xd0, 0xbe, 0x0c, 0xa1, 0x05, 0x7b, 0x68, 0xf3, 0x56, 0x3b, 0x63, 0xb4, 0x2a, 0x2c, 0x74, 0xf0,
	0x4d, 0x0c, 0x55, 0xb2, 0xa2, 0x47, 0x6d, 0x1b, 0xce, 0x73, 0x0c, 0x42, 0x47, 0x4c, 0x31, 0x8b,
	0x52, 0x69, 0xbc, 0x27, 0x50, 0x1d, 0xcc, 0x61, 0x54, 0x94, 0x19, 0x73, 0x9a, 0x50, 0x4c, 0x8a,
	0x3d, 0x9d, 0xbf, 0xd5, 0x31, 0xa8, 0x64, 0x58, 0x2b, 0x95, 0x45, 0xf5, 0x52, 0x53, 0x89, 0x72,
	0xa8, 0x9a, 0x33, 0x53, 0x7d, 0x22, 0x50, 0x57, 0xa9, 0x76, 0xd0, 0xc1, 0x99, 0x63, 0xfd, 0x24,
	0xa0, 0xab, 0x58, 0x33, 0x2e, 0xe6, 0x81, 0x83, 0xe4, 0x1f, 0x3c, 0xd5, 0xc1, 0x6f, 0x02, 0xba,
	0xd5, 0xdf, 0x35, 0x1e, 0xa1, 0xcd, 0x67, 0xec, 0xe0, 0x09, 0x54, 0x47, 0x76, 0x31, 0x59, 0x4f,
	0xeb, 0x13, 0xbc, 0x0c, 0x83, 0x5b, 0xcb, 0x5c, 0x35, 0x62, 0xfc, 0x20, 0xb0, 0x3a, 0xa2, 0xc9,
	0xc5, 0xdb, 0x24, 0xe6, 0xc4, 0xe5, 0xd9, 0x99, 0xbf, 0x12, 0x58, 0x51, 0x35, 0xd9, 0x6f, 0xa5,
	0x8f, 0x61, 0x79, 0x84, 0x77, 0x5a, 0xdc, 0x8a, 0x8a, 0x6b, 0x7c, 0x23, 0x50, 0x53, 0x25, 0x39,
	0xac, 0x16, 0xd9, 0xe1, 0x7e, 0x27, 0x50, 0x57, 0x25, 0x79, 0x2c, 0x23, 0x79, 0xf2, 0xbe, 0xe8,
	0xbe, 0xf4, 0xe7, 0x97, 0xf7, 0x78, 0xac, 0xe0, 0x76, 0xfc, 0x23, 0x6f, 0x9e, 0x89, 0xff, 0x10,
	0xb8, 0xac, 0x4a, 0xfe, 0xd3, 0x71, 0x61, 0xf8, 0xe0, 0x58, 0x98, 0xfa, 0xe0, 0x38, 0x71, 0xa9,
	0x59, 0xfc, 0xc7, 0xe5, 0xf1, 0x2d, 0x81, 0xf2, 0x73, 0xce, 0xba, 0xcf, 0x1c, 0xdb, 0xf3, 0x32,
	0x36, 0x7c, 0x1d, 0x0a, 0xd1, 0x2d, 0x22, 0xfd, 0x2c, 0xf5, 0x31, 0xb6, 0x68, 0x5c, 0x2b, 0x96,
	0x18, 0xef, 0x08, 0x2c, 0x45, 0xcd, 0x07, 0xb6, 0xd7, 0x42, 0xc7, 0x99, 0x1d, 0xc8, 0x31, 0x81,
	0x4a, 0xd4, 0x9c, 0xf1, 0x0e, 0x28, 0x89, 0x93, 0x5d, 0xef, 0x24, 0xe2, 0xfb, 0x77, 0x5f, 0xdd,
	0x39, 0x64, 0xa2, 0x1d, 0x1e, 0x34, 0x5b, 0xbe, 0x6b, 0x32, 0xa7, 0x6d, 0xbb, 0x6e, 0x9b, 0x52,
	0xb3, 0x13, 0x52, 0xbb, 0xc3, 0xb6, 0xc2, 0x00, 0xf9, 0x56, 0x80, 0xbc, 0xc7, 0x5a, 0x68, 0xa2,
	0x27, 0x98, 0x60, 0x18, 0x98, 0xc9, 0xa5, 0xf3, 0xa0, 0x18, 0x5f, 0xda, 0xb6, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x74, 0x58, 0x0a, 0x85, 0x0e, 0x00, 0x00,
}
