// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/rental.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	rental "github.com/ilhammhdd/kudaki-user-service/entities/domains/rental"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemAddedToStorefront struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Item                 *rental.Item         `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemAddedToStorefront) Reset()         { *m = ItemAddedToStorefront{} }
func (m *ItemAddedToStorefront) String() string { return proto.CompactTextString(m) }
func (*ItemAddedToStorefront) ProtoMessage()    {}
func (*ItemAddedToStorefront) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{0}
}

func (m *ItemAddedToStorefront) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAddedToStorefront.Unmarshal(m, b)
}
func (m *ItemAddedToStorefront) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAddedToStorefront.Marshal(b, m, deterministic)
}
func (m *ItemAddedToStorefront) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAddedToStorefront.Merge(m, src)
}
func (m *ItemAddedToStorefront) XXX_Size() int {
	return xxx_messageInfo_ItemAddedToStorefront.Size(m)
}
func (m *ItemAddedToStorefront) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAddedToStorefront.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAddedToStorefront proto.InternalMessageInfo

func (m *ItemAddedToStorefront) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ItemAddedToStorefront) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemAddedToStorefront) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type StorefrontItemEdited struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OldItem              *rental.Item         `protobuf:"bytes,3,opt,name=old_item,json=oldItem,proto3" json:"old_item,omitempty"`
	NewItem              *rental.Item         `protobuf:"bytes,4,opt,name=new_item,json=newItem,proto3" json:"new_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorefrontItemEdited) Reset()         { *m = StorefrontItemEdited{} }
func (m *StorefrontItemEdited) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemEdited) ProtoMessage()    {}
func (*StorefrontItemEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{1}
}

func (m *StorefrontItemEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemEdited.Unmarshal(m, b)
}
func (m *StorefrontItemEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemEdited.Marshal(b, m, deterministic)
}
func (m *StorefrontItemEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemEdited.Merge(m, src)
}
func (m *StorefrontItemEdited) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemEdited.Size(m)
}
func (m *StorefrontItemEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemEdited.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemEdited proto.InternalMessageInfo

func (m *StorefrontItemEdited) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StorefrontItemEdited) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemEdited) GetOldItem() *rental.Item {
	if m != nil {
		return m.OldItem
	}
	return nil
}

func (m *StorefrontItemEdited) GetNewItem() *rental.Item {
	if m != nil {
		return m.NewItem
	}
	return nil
}

type StorefrontItemsRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	UserUuid             string               `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Items                []*rental.Item       `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorefrontItemsRetrieved) Reset()         { *m = StorefrontItemsRetrieved{} }
func (m *StorefrontItemsRetrieved) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemsRetrieved) ProtoMessage()    {}
func (*StorefrontItemsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{2}
}

func (m *StorefrontItemsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemsRetrieved.Unmarshal(m, b)
}
func (m *StorefrontItemsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemsRetrieved.Marshal(b, m, deterministic)
}
func (m *StorefrontItemsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemsRetrieved.Merge(m, src)
}
func (m *StorefrontItemsRetrieved) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemsRetrieved.Size(m)
}
func (m *StorefrontItemsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemsRetrieved proto.InternalMessageInfo

func (m *StorefrontItemsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StorefrontItemsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemsRetrieved) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *StorefrontItemsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *StorefrontItemsRetrieved) GetItems() []*rental.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type StorefrontItemDeleted struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Item                 *rental.Item         `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorefrontItemDeleted) Reset()         { *m = StorefrontItemDeleted{} }
func (m *StorefrontItemDeleted) String() string { return proto.CompactTextString(m) }
func (*StorefrontItemDeleted) ProtoMessage()    {}
func (*StorefrontItemDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{3}
}

func (m *StorefrontItemDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontItemDeleted.Unmarshal(m, b)
}
func (m *StorefrontItemDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontItemDeleted.Marshal(b, m, deterministic)
}
func (m *StorefrontItemDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontItemDeleted.Merge(m, src)
}
func (m *StorefrontItemDeleted) XXX_Size() int {
	return xxx_messageInfo_StorefrontItemDeleted.Size(m)
}
func (m *StorefrontItemDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontItemDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontItemDeleted proto.InternalMessageInfo

func (m *StorefrontItemDeleted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StorefrontItemDeleted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *StorefrontItemDeleted) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type RentalsHistoryRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	UserUuid             string               `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Rentals              []*rental.Rental     `protobuf:"bytes,5,rep,name=rentals,proto3" json:"rentals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RentalsHistoryRetrieved) Reset()         { *m = RentalsHistoryRetrieved{} }
func (m *RentalsHistoryRetrieved) String() string { return proto.CompactTextString(m) }
func (*RentalsHistoryRetrieved) ProtoMessage()    {}
func (*RentalsHistoryRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{4}
}

func (m *RentalsHistoryRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RentalsHistoryRetrieved.Unmarshal(m, b)
}
func (m *RentalsHistoryRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RentalsHistoryRetrieved.Marshal(b, m, deterministic)
}
func (m *RentalsHistoryRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RentalsHistoryRetrieved.Merge(m, src)
}
func (m *RentalsHistoryRetrieved) XXX_Size() int {
	return xxx_messageInfo_RentalsHistoryRetrieved.Size(m)
}
func (m *RentalsHistoryRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_RentalsHistoryRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_RentalsHistoryRetrieved proto.InternalMessageInfo

func (m *RentalsHistoryRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RentalsHistoryRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RentalsHistoryRetrieved) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *RentalsHistoryRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RentalsHistoryRetrieved) GetRentals() []*rental.Rental {
	if m != nil {
		return m.Rentals
	}
	return nil
}

type RentalHistoryRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Rental               *rental.Rental       `protobuf:"bytes,3,opt,name=rental,proto3" json:"rental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RentalHistoryRetrieved) Reset()         { *m = RentalHistoryRetrieved{} }
func (m *RentalHistoryRetrieved) String() string { return proto.CompactTextString(m) }
func (*RentalHistoryRetrieved) ProtoMessage()    {}
func (*RentalHistoryRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{5}
}

func (m *RentalHistoryRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RentalHistoryRetrieved.Unmarshal(m, b)
}
func (m *RentalHistoryRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RentalHistoryRetrieved.Marshal(b, m, deterministic)
}
func (m *RentalHistoryRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RentalHistoryRetrieved.Merge(m, src)
}
func (m *RentalHistoryRetrieved) XXX_Size() int {
	return xxx_messageInfo_RentalHistoryRetrieved.Size(m)
}
func (m *RentalHistoryRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_RentalHistoryRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_RentalHistoryRetrieved proto.InternalMessageInfo

func (m *RentalHistoryRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RentalHistoryRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RentalHistoryRetrieved) GetRental() *rental.Rental {
	if m != nil {
		return m.Rental
	}
	return nil
}

type RentalAccepted struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Rental               *rental.Rental       `protobuf:"bytes,3,opt,name=rental,proto3" json:"rental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RentalAccepted) Reset()         { *m = RentalAccepted{} }
func (m *RentalAccepted) String() string { return proto.CompactTextString(m) }
func (*RentalAccepted) ProtoMessage()    {}
func (*RentalAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{6}
}

func (m *RentalAccepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RentalAccepted.Unmarshal(m, b)
}
func (m *RentalAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RentalAccepted.Marshal(b, m, deterministic)
}
func (m *RentalAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RentalAccepted.Merge(m, src)
}
func (m *RentalAccepted) XXX_Size() int {
	return xxx_messageInfo_RentalAccepted.Size(m)
}
func (m *RentalAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_RentalAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_RentalAccepted proto.InternalMessageInfo

func (m *RentalAccepted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RentalAccepted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RentalAccepted) GetRental() *rental.Rental {
	if m != nil {
		return m.Rental
	}
	return nil
}

type RentalDeclined struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Rental               *rental.Rental       `protobuf:"bytes,3,opt,name=rental,proto3" json:"rental,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RentalDeclined) Reset()         { *m = RentalDeclined{} }
func (m *RentalDeclined) String() string { return proto.CompactTextString(m) }
func (*RentalDeclined) ProtoMessage()    {}
func (*RentalDeclined) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{7}
}

func (m *RentalDeclined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RentalDeclined.Unmarshal(m, b)
}
func (m *RentalDeclined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RentalDeclined.Marshal(b, m, deterministic)
}
func (m *RentalDeclined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RentalDeclined.Merge(m, src)
}
func (m *RentalDeclined) XXX_Size() int {
	return xxx_messageInfo_RentalDeclined.Size(m)
}
func (m *RentalDeclined) XXX_DiscardUnknown() {
	xxx_messageInfo_RentalDeclined.DiscardUnknown(m)
}

var xxx_messageInfo_RentalDeclined proto.InternalMessageInfo

func (m *RentalDeclined) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RentalDeclined) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *RentalDeclined) GetRental() *rental.Rental {
	if m != nil {
		return m.Rental
	}
	return nil
}

type ItemAddedToCart struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Cart                 *rental.Cart         `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	Item                 *rental.Item         `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemAddedToCart) Reset()         { *m = ItemAddedToCart{} }
func (m *ItemAddedToCart) String() string { return proto.CompactTextString(m) }
func (*ItemAddedToCart) ProtoMessage()    {}
func (*ItemAddedToCart) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{8}
}

func (m *ItemAddedToCart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAddedToCart.Unmarshal(m, b)
}
func (m *ItemAddedToCart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAddedToCart.Marshal(b, m, deterministic)
}
func (m *ItemAddedToCart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAddedToCart.Merge(m, src)
}
func (m *ItemAddedToCart) XXX_Size() int {
	return xxx_messageInfo_ItemAddedToCart.Size(m)
}
func (m *ItemAddedToCart) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAddedToCart.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAddedToCart proto.InternalMessageInfo

func (m *ItemAddedToCart) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ItemAddedToCart) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemAddedToCart) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *ItemAddedToCart) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CartItemEdited struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Cart                 *rental.Cart         `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CartItemEdited) Reset()         { *m = CartItemEdited{} }
func (m *CartItemEdited) String() string { return proto.CompactTextString(m) }
func (*CartItemEdited) ProtoMessage()    {}
func (*CartItemEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{9}
}

func (m *CartItemEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemEdited.Unmarshal(m, b)
}
func (m *CartItemEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemEdited.Marshal(b, m, deterministic)
}
func (m *CartItemEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemEdited.Merge(m, src)
}
func (m *CartItemEdited) XXX_Size() int {
	return xxx_messageInfo_CartItemEdited.Size(m)
}
func (m *CartItemEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemEdited.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemEdited proto.InternalMessageInfo

func (m *CartItemEdited) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartItemEdited) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CartItemEdited) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type CartItemDeleted struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Cart                 *rental.Cart         `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CartItemDeleted) Reset()         { *m = CartItemDeleted{} }
func (m *CartItemDeleted) String() string { return proto.CompactTextString(m) }
func (*CartItemDeleted) ProtoMessage()    {}
func (*CartItemDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{10}
}

func (m *CartItemDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemDeleted.Unmarshal(m, b)
}
func (m *CartItemDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemDeleted.Marshal(b, m, deterministic)
}
func (m *CartItemDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemDeleted.Merge(m, src)
}
func (m *CartItemDeleted) XXX_Size() int {
	return xxx_messageInfo_CartItemDeleted.Size(m)
}
func (m *CartItemDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemDeleted proto.InternalMessageInfo

func (m *CartItemDeleted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartItemDeleted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CartItemDeleted) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type CartItemsRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	UserUuid             string               `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Filter               *domains.Filter      `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Carts                []*rental.Cart       `protobuf:"bytes,5,rep,name=carts,proto3" json:"carts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CartItemsRetrieved) Reset()         { *m = CartItemsRetrieved{} }
func (m *CartItemsRetrieved) String() string { return proto.CompactTextString(m) }
func (*CartItemsRetrieved) ProtoMessage()    {}
func (*CartItemsRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{11}
}

func (m *CartItemsRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemsRetrieved.Unmarshal(m, b)
}
func (m *CartItemsRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemsRetrieved.Marshal(b, m, deterministic)
}
func (m *CartItemsRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemsRetrieved.Merge(m, src)
}
func (m *CartItemsRetrieved) XXX_Size() int {
	return xxx_messageInfo_CartItemsRetrieved.Size(m)
}
func (m *CartItemsRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemsRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemsRetrieved proto.InternalMessageInfo

func (m *CartItemsRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartItemsRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CartItemsRetrieved) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *CartItemsRetrieved) GetFilter() *domains.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *CartItemsRetrieved) GetCarts() []*rental.Cart {
	if m != nil {
		return m.Carts
	}
	return nil
}

type CartItemsBooked struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Cart                 *rental.Cart         `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CartItemsBooked) Reset()         { *m = CartItemsBooked{} }
func (m *CartItemsBooked) String() string { return proto.CompactTextString(m) }
func (*CartItemsBooked) ProtoMessage()    {}
func (*CartItemsBooked) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{12}
}

func (m *CartItemsBooked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemsBooked.Unmarshal(m, b)
}
func (m *CartItemsBooked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemsBooked.Marshal(b, m, deterministic)
}
func (m *CartItemsBooked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemsBooked.Merge(m, src)
}
func (m *CartItemsBooked) XXX_Size() int {
	return xxx_messageInfo_CartItemsBooked.Size(m)
}
func (m *CartItemsBooked) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemsBooked.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemsBooked proto.InternalMessageInfo

func (m *CartItemsBooked) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CartItemsBooked) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CartItemsBooked) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type OwnersContactedForAcceptance struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Users                []*user.User         `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Cart                 *rental.Cart         `protobuf:"bytes,4,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OwnersContactedForAcceptance) Reset()         { *m = OwnersContactedForAcceptance{} }
func (m *OwnersContactedForAcceptance) String() string { return proto.CompactTextString(m) }
func (*OwnersContactedForAcceptance) ProtoMessage()    {}
func (*OwnersContactedForAcceptance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{13}
}

func (m *OwnersContactedForAcceptance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnersContactedForAcceptance.Unmarshal(m, b)
}
func (m *OwnersContactedForAcceptance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnersContactedForAcceptance.Marshal(b, m, deterministic)
}
func (m *OwnersContactedForAcceptance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnersContactedForAcceptance.Merge(m, src)
}
func (m *OwnersContactedForAcceptance) XXX_Size() int {
	return xxx_messageInfo_OwnersContactedForAcceptance.Size(m)
}
func (m *OwnersContactedForAcceptance) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnersContactedForAcceptance.DiscardUnknown(m)
}

var xxx_messageInfo_OwnersContactedForAcceptance proto.InternalMessageInfo

func (m *OwnersContactedForAcceptance) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OwnersContactedForAcceptance) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnersContactedForAcceptance) GetUsers() []*user.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *OwnersContactedForAcceptance) GetCart() *rental.Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type ItemRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Item                 *rental.Item         `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemRetrieved) Reset()         { *m = ItemRetrieved{} }
func (m *ItemRetrieved) String() string { return proto.CompactTextString(m) }
func (*ItemRetrieved) ProtoMessage()    {}
func (*ItemRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8d01722d54fb2c6, []int{14}
}

func (m *ItemRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRetrieved.Unmarshal(m, b)
}
func (m *ItemRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRetrieved.Marshal(b, m, deterministic)
}
func (m *ItemRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRetrieved.Merge(m, src)
}
func (m *ItemRetrieved) XXX_Size() int {
	return xxx_messageInfo_ItemRetrieved.Size(m)
}
func (m *ItemRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRetrieved proto.InternalMessageInfo

func (m *ItemRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ItemRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ItemRetrieved) GetItem() *rental.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemAddedToStorefront)(nil), "event.ItemAddedToStorefront")
	proto.RegisterType((*StorefrontItemEdited)(nil), "event.StorefrontItemEdited")
	proto.RegisterType((*StorefrontItemsRetrieved)(nil), "event.StorefrontItemsRetrieved")
	proto.RegisterType((*StorefrontItemDeleted)(nil), "event.StorefrontItemDeleted")
	proto.RegisterType((*RentalsHistoryRetrieved)(nil), "event.RentalsHistoryRetrieved")
	proto.RegisterType((*RentalHistoryRetrieved)(nil), "event.RentalHistoryRetrieved")
	proto.RegisterType((*RentalAccepted)(nil), "event.RentalAccepted")
	proto.RegisterType((*RentalDeclined)(nil), "event.RentalDeclined")
	proto.RegisterType((*ItemAddedToCart)(nil), "event.ItemAddedToCart")
	proto.RegisterType((*CartItemEdited)(nil), "event.CartItemEdited")
	proto.RegisterType((*CartItemDeleted)(nil), "event.CartItemDeleted")
	proto.RegisterType((*CartItemsRetrieved)(nil), "event.CartItemsRetrieved")
	proto.RegisterType((*CartItemsBooked)(nil), "event.CartItemsBooked")
	proto.RegisterType((*OwnersContactedForAcceptance)(nil), "event.OwnersContactedForAcceptance")
	proto.RegisterType((*ItemRetrieved)(nil), "event.ItemRetrieved")
}

func init() { proto.RegisterFile("events/rental.proto", fileDescriptor_a8d01722d54fb2c6) }

var fileDescriptor_a8d01722d54fb2c6 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xbd, 0x6e, 0x13, 0x41,
	0x10, 0xd6, 0xe2, 0x9f, 0x24, 0x13, 0x70, 0xc4, 0x25, 0x21, 0x87, 0x43, 0x61, 0x5d, 0x01, 0xa1,
	0xb0, 0x4f, 0x02, 0x09, 0x21, 0xba, 0xfc, 0x0a, 0x2a, 0xa4, 0x0b, 0x69, 0x68, 0xac, 0xcb, 0xed,
	0x04, 0xaf, 0x7c, 0xb7, 0x1b, 0xed, 0xee, 0xd9, 0xa2, 0x07, 0x1a, 0xe8, 0x78, 0x10, 0x5e, 0x80,
	0x8a, 0x27, 0xa0, 0xa2, 0xe1, 0x65, 0xd0, 0xee, 0xde, 0x39, 0x71, 0x24, 0x63, 0x17, 0xb6, 0xe2,
	0xc6, 0x3a, 0xcf, 0xf7, 0xed, 0xcc, 0xf7, 0xcd, 0xed, 0xce, 0x2d, 0x6c, 0xe2, 0x00, 0xb9, 0x56,
	0xa1, 0x44, 0xae, 0xe3, 0xb4, 0x73, 0x29, 0x85, 0x16, 0x5e, 0xcd, 0x06, 0x9b, 0x3b, 0x54, 0x64,
	0x31, 0xe3, 0x2a, 0xcc, 0x15, 0x4a, 0xfb, 0xe3, 0xf0, 0xe6, 0xc3, 0x12, 0x70, 0xab, 0x42, 0xa6,
	0x31, 0x9b, 0x00, 0x25, 0xb1, 0xd4, 0x05, 0xb4, 0x7b, 0x03, 0xba, 0x5e, 0xb2, 0xb9, 0x55, 0x82,
	0x17, 0x2c, 0xd5, 0xa3, 0x42, 0xa3, 0xa8, 0xd2, 0xb1, 0xce, 0x95, 0x8b, 0x06, 0xdf, 0x08, 0x6c,
	0xbf, 0xd1, 0x98, 0xed, 0x53, 0x8a, 0xf4, 0x9d, 0x38, 0xd5, 0x42, 0xe2, 0x85, 0x14, 0x5c, 0x7b,
	0x1e, 0x54, 0xf3, 0x9c, 0x51, 0x9f, 0xb4, 0xc8, 0xde, 0x5a, 0x64, 0x9f, 0xbd, 0x17, 0x70, 0xd7,
	0xda, 0xe9, 0xba, 0x1c, 0xfe, 0x9d, 0x16, 0xd9, 0x5b, 0x7f, 0xb6, 0xd9, 0x71, 0xa9, 0x3b, 0xc7,
	0x06, 0x3b, 0xb5, 0x50, 0xb4, 0x8e, 0x57, 0x7f, 0xbc, 0x27, 0x50, 0x35, 0xbe, 0xfc, 0xca, 0x38,
	0xbf, 0x50, 0x6d, 0xea, 0x47, 0x96, 0x10, 0xfc, 0x22, 0xb0, 0x75, 0xa5, 0xc1, 0x00, 0xc7, 0x94,
	0x69, 0xa4, 0x73, 0x55, 0xd3, 0x81, 0x55, 0x91, 0xd2, 0xee, 0x34, 0x45, 0x2b, 0x22, 0xa5, 0xe6,
	0xc1, 0xf0, 0x39, 0x0e, 0x1d, 0xbf, 0xfa, 0x1f, 0x3e, 0xc7, 0xa1, 0x79, 0x08, 0xfe, 0x10, 0xf0,
	0xc7, 0x4d, 0xa8, 0x08, 0xb5, 0x64, 0x38, 0x98, 0xb3, 0x91, 0x5d, 0x58, 0x33, 0x3b, 0xa9, 0x6b,
	0x13, 0x56, 0x6c, 0xc2, 0x55, 0x13, 0x38, 0x33, 0x49, 0x1f, 0x43, 0xdd, 0xbd, 0xff, 0x42, 0x73,
	0xa3, 0x4c, 0x77, 0x62, 0xa3, 0x51, 0x81, 0x7a, 0x4f, 0xa1, 0x66, 0x9c, 0x29, 0xbf, 0xd6, 0xaa,
	0x4c, 0xb2, 0xe6, 0x18, 0x76, 0xb3, 0x8c, 0x1b, 0x3b, 0xc2, 0x14, 0xe7, 0xfd, 0x7a, 0x66, 0xde,
	0x2c, 0x7f, 0x09, 0xec, 0x44, 0x36, 0xaa, 0x5e, 0x33, 0xa5, 0x85, 0xfc, 0xb8, 0xc4, 0x6d, 0x0e,
	0x61, 0xc5, 0x39, 0x28, 0x1b, 0xbd, 0x7d, 0xc3, 0x98, 0x73, 0x12, 0x95, 0xac, 0xe0, 0x3b, 0x81,
	0x07, 0x2e, 0xb6, 0x50, 0x73, 0x6d, 0xa8, 0xbb, 0x8a, 0x45, 0xbf, 0x27, 0xc8, 0x2a, 0x48, 0xc1,
	0x57, 0x02, 0x0d, 0x17, 0xda, 0x4f, 0x12, 0xbc, 0xd4, 0xcb, 0xa2, 0xe6, 0x08, 0x93, 0x94, 0xf1,
	0xdb, 0x55, 0xf3, 0x83, 0xc0, 0xc6, 0xb5, 0x59, 0x7a, 0x18, 0xcb, 0xb9, 0x4f, 0x51, 0xf3, 0x09,
	0x98, 0x70, 0x30, 0x4c, 0xb9, 0xc8, 0x12, 0x46, 0x27, 0xa8, 0x3a, 0xed, 0x04, 0x7d, 0x26, 0xd0,
	0x30, 0xeb, 0x16, 0x34, 0x68, 0x67, 0x15, 0x1c, 0x7c, 0x21, 0xb0, 0x51, 0xea, 0x58, 0xd0, 0x48,
	0x99, 0x4d, 0xc8, 0x6f, 0x02, 0x5e, 0x29, 0x64, 0xc9, 0x87, 0xb6, 0xd1, 0x3b, 0x69, 0x68, 0x5b,
	0x47, 0x8e, 0x31, 0xd6, 0x5b, 0x75, 0x20, 0x44, 0xff, 0xb6, 0x7a, 0xfb, 0x93, 0xc0, 0xa3, 0xb7,
	0x43, 0x8e, 0x52, 0x1d, 0x0a, 0xae, 0xe3, 0x44, 0x23, 0x3d, 0x11, 0xd2, 0x8d, 0x91, 0x98, 0x27,
	0x38, 0x67, 0x55, 0x35, 0xd3, 0x54, 0xe5, 0x57, 0x6c, 0x83, 0xee, 0x97, 0x0b, 0xec, 0xcd, 0xeb,
	0x4c, 0xa1, 0x8c, 0x1c, 0x3e, 0x92, 0x5f, 0x9d, 0x26, 0xff, 0x13, 0x81, 0x7b, 0xf6, 0xe8, 0x2c,
	0x64, 0x57, 0xcc, 0xfa, 0xd1, 0x3b, 0x78, 0xf5, 0xfe, 0xe5, 0x07, 0xa6, 0x7b, 0xf9, 0x79, 0x27,
	0x11, 0x59, 0xc8, 0xd2, 0x5e, 0x9c, 0x65, 0x3d, 0x4a, 0xc3, 0x7e, 0x4e, 0xe3, 0x3e, 0x6b, 0x1b,
	0x53, 0x6d, 0x85, 0x72, 0xc0, 0x12, 0x0c, 0x91, 0x6b, 0xa6, 0x19, 0xaa, 0xd0, 0x5d, 0x4c, 0xcf,
	0xeb, 0xf6, 0xce, 0xf7, 0xfc, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xc8, 0x67, 0x43, 0xa9,
	0x0a, 0x00, 0x00,
}
