// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/user.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	domains "github.com/ilhammhdd/kudaki-user-service/entities/domains"
	user "github.com/ilhammhdd/kudaki-user-service/entities/domains/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignedUp struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Profile              *user.Profile        `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	User                 *user.User           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignedUp) Reset()         { *m = SignedUp{} }
func (m *SignedUp) String() string { return proto.CompactTextString(m) }
func (*SignedUp) ProtoMessage()    {}
func (*SignedUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{0}
}

func (m *SignedUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedUp.Unmarshal(m, b)
}
func (m *SignedUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedUp.Marshal(b, m, deterministic)
}
func (m *SignedUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedUp.Merge(m, src)
}
func (m *SignedUp) XXX_Size() int {
	return xxx_messageInfo_SignedUp.Size(m)
}
func (m *SignedUp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedUp.DiscardUnknown(m)
}

var xxx_messageInfo_SignedUp proto.InternalMessageInfo

func (m *SignedUp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignedUp) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *SignedUp) GetProfile() *user.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SignedUp) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignedIn struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignedIn) Reset()         { *m = SignedIn{} }
func (m *SignedIn) String() string { return proto.CompactTextString(m) }
func (*SignedIn) ProtoMessage()    {}
func (*SignedIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{1}
}

func (m *SignedIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedIn.Unmarshal(m, b)
}
func (m *SignedIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedIn.Marshal(b, m, deterministic)
}
func (m *SignedIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedIn.Merge(m, src)
}
func (m *SignedIn) XXX_Size() int {
	return xxx_messageInfo_SignedIn.Size(m)
}
func (m *SignedIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignedIn proto.InternalMessageInfo

func (m *SignedIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignedIn) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *SignedIn) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignedOut struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignedOut) Reset()         { *m = SignedOut{} }
func (m *SignedOut) String() string { return proto.CompactTextString(m) }
func (*SignedOut) ProtoMessage()    {}
func (*SignedOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{2}
}

func (m *SignedOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedOut.Unmarshal(m, b)
}
func (m *SignedOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedOut.Marshal(b, m, deterministic)
}
func (m *SignedOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedOut.Merge(m, src)
}
func (m *SignedOut) XXX_Size() int {
	return xxx_messageInfo_SignedOut.Size(m)
}
func (m *SignedOut) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedOut.DiscardUnknown(m)
}

var xxx_messageInfo_SignedOut proto.InternalMessageInfo

func (m *SignedOut) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SignedOut) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *SignedOut) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type AccountDeleted struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountDeleted) Reset()         { *m = AccountDeleted{} }
func (m *AccountDeleted) String() string { return proto.CompactTextString(m) }
func (*AccountDeleted) ProtoMessage()    {}
func (*AccountDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{3}
}

func (m *AccountDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeleted.Unmarshal(m, b)
}
func (m *AccountDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeleted.Marshal(b, m, deterministic)
}
func (m *AccountDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeleted.Merge(m, src)
}
func (m *AccountDeleted) XXX_Size() int {
	return xxx_messageInfo_AccountDeleted.Size(m)
}
func (m *AccountDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeleted proto.InternalMessageInfo

func (m *AccountDeleted) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AccountDeleted) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *AccountDeleted) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

type ProfileUpdated struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OldProfile           *user.Profile        `protobuf:"bytes,3,opt,name=old_profile,json=oldProfile,proto3" json:"old_profile,omitempty"`
	NewProfile           *user.Profile        `protobuf:"bytes,4,opt,name=new_profile,json=newProfile,proto3" json:"new_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileUpdated) Reset()         { *m = ProfileUpdated{} }
func (m *ProfileUpdated) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdated) ProtoMessage()    {}
func (*ProfileUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{4}
}

func (m *ProfileUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdated.Unmarshal(m, b)
}
func (m *ProfileUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdated.Marshal(b, m, deterministic)
}
func (m *ProfileUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdated.Merge(m, src)
}
func (m *ProfileUpdated) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdated.Size(m)
}
func (m *ProfileUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdated proto.InternalMessageInfo

func (m *ProfileUpdated) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProfileUpdated) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ProfileUpdated) GetOldProfile() *user.Profile {
	if m != nil {
		return m.OldProfile
	}
	return nil
}

func (m *ProfileUpdated) GetNewProfile() *user.Profile {
	if m != nil {
		return m.NewProfile
	}
	return nil
}

type PasswordChanged struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OldUser              *user.User           `protobuf:"bytes,3,opt,name=old_user,json=oldUser,proto3" json:"old_user,omitempty"`
	NewUser              *user.User           `protobuf:"bytes,4,opt,name=new_user,json=newUser,proto3" json:"new_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PasswordChanged) Reset()         { *m = PasswordChanged{} }
func (m *PasswordChanged) String() string { return proto.CompactTextString(m) }
func (*PasswordChanged) ProtoMessage()    {}
func (*PasswordChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{5}
}

func (m *PasswordChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordChanged.Unmarshal(m, b)
}
func (m *PasswordChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordChanged.Marshal(b, m, deterministic)
}
func (m *PasswordChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordChanged.Merge(m, src)
}
func (m *PasswordChanged) XXX_Size() int {
	return xxx_messageInfo_PasswordChanged.Size(m)
}
func (m *PasswordChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordChanged.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordChanged proto.InternalMessageInfo

func (m *PasswordChanged) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PasswordChanged) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *PasswordChanged) GetOldUser() *user.User {
	if m != nil {
		return m.OldUser
	}
	return nil
}

func (m *PasswordChanged) GetNewUser() *user.User {
	if m != nil {
		return m.NewUser
	}
	return nil
}

type UsersSearched struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Key                  string               `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Users                []*user.User         `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UsersSearched) Reset()         { *m = UsersSearched{} }
func (m *UsersSearched) String() string { return proto.CompactTextString(m) }
func (*UsersSearched) ProtoMessage()    {}
func (*UsersSearched) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{6}
}

func (m *UsersSearched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersSearched.Unmarshal(m, b)
}
func (m *UsersSearched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersSearched.Marshal(b, m, deterministic)
}
func (m *UsersSearched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersSearched.Merge(m, src)
}
func (m *UsersSearched) XXX_Size() int {
	return xxx_messageInfo_UsersSearched.Size(m)
}
func (m *UsersSearched) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersSearched.DiscardUnknown(m)
}

var xxx_messageInfo_UsersSearched proto.InternalMessageInfo

func (m *UsersSearched) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UsersSearched) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *UsersSearched) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UsersSearched) GetUsers() []*user.User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UsersRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Users                []*user.User         `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UsersRetrieved) Reset()         { *m = UsersRetrieved{} }
func (m *UsersRetrieved) String() string { return proto.CompactTextString(m) }
func (*UsersRetrieved) ProtoMessage()    {}
func (*UsersRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{7}
}

func (m *UsersRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRetrieved.Unmarshal(m, b)
}
func (m *UsersRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRetrieved.Marshal(b, m, deterministic)
}
func (m *UsersRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRetrieved.Merge(m, src)
}
func (m *UsersRetrieved) XXX_Size() int {
	return xxx_messageInfo_UsersRetrieved.Size(m)
}
func (m *UsersRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRetrieved proto.InternalMessageInfo

func (m *UsersRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UsersRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *UsersRetrieved) GetUsers() []*user.User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ProfileRetrieved struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	UserUuid             string               `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Profiles             []*user.Profile      `protobuf:"bytes,4,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileRetrieved) Reset()         { *m = ProfileRetrieved{} }
func (m *ProfileRetrieved) String() string { return proto.CompactTextString(m) }
func (*ProfileRetrieved) ProtoMessage()    {}
func (*ProfileRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{8}
}

func (m *ProfileRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRetrieved.Unmarshal(m, b)
}
func (m *ProfileRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRetrieved.Marshal(b, m, deterministic)
}
func (m *ProfileRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRetrieved.Merge(m, src)
}
func (m *ProfileRetrieved) XXX_Size() int {
	return xxx_messageInfo_ProfileRetrieved.Size(m)
}
func (m *ProfileRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRetrieved proto.InternalMessageInfo

func (m *ProfileRetrieved) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProfileRetrieved) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ProfileRetrieved) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *ProfileRetrieved) GetProfiles() []*user.Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type PaymentDone struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventStatus          *domains.EventStatus `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Payment              *user.Payment        `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentDone) Reset()         { *m = PaymentDone{} }
func (m *PaymentDone) String() string { return proto.CompactTextString(m) }
func (*PaymentDone) ProtoMessage()    {}
func (*PaymentDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{9}
}

func (m *PaymentDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentDone.Unmarshal(m, b)
}
func (m *PaymentDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentDone.Marshal(b, m, deterministic)
}
func (m *PaymentDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentDone.Merge(m, src)
}
func (m *PaymentDone) XXX_Size() int {
	return xxx_messageInfo_PaymentDone.Size(m)
}
func (m *PaymentDone) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentDone.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentDone proto.InternalMessageInfo

func (m *PaymentDone) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PaymentDone) GetEventStatus() *domains.EventStatus {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *PaymentDone) GetPayment() *user.Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*SignedUp)(nil), "event.SignedUp")
	proto.RegisterType((*SignedIn)(nil), "event.SignedIn")
	proto.RegisterType((*SignedOut)(nil), "event.SignedOut")
	proto.RegisterType((*AccountDeleted)(nil), "event.AccountDeleted")
	proto.RegisterType((*ProfileUpdated)(nil), "event.ProfileUpdated")
	proto.RegisterType((*PasswordChanged)(nil), "event.PasswordChanged")
	proto.RegisterType((*UsersSearched)(nil), "event.UsersSearched")
	proto.RegisterType((*UsersRetrieved)(nil), "event.UsersRetrieved")
	proto.RegisterType((*ProfileRetrieved)(nil), "event.ProfileRetrieved")
	proto.RegisterType((*PaymentDone)(nil), "event.PaymentDone")
}

func init() { proto.RegisterFile("events/user.proto", fileDescriptor_f16fa325116cd758) }

var fileDescriptor_f16fa325116cd758 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x65, 0x9a, 0xa5, 0xed, 0x14, 0xca, 0x6e, 0x58, 0x89, 0xa8, 0x5c, 0xaa, 0x48, 0x88,
	0x3d, 0xb0, 0x09, 0x02, 0x81, 0x10, 0x37, 0x60, 0x39, 0x70, 0xa2, 0x4a, 0xd5, 0x0b, 0x97, 0xca,
	0x1b, 0x0f, 0x8d, 0xd5, 0xc4, 0xae, 0x62, 0xa7, 0xd5, 0x1e, 0xe0, 0x82, 0x38, 0xf0, 0x02, 0xbc,
	0xc5, 0x3e, 0x00, 0xaf, 0xc0, 0x53, 0x21, 0xdb, 0x49, 0x61, 0xa5, 0xaa, 0x70, 0x08, 0xda, 0xdb,
	0xc4, 0xff, 0xfc, 0x33, 0xdf, 0x38, 0x4e, 0x0c, 0x47, 0xb8, 0x46, 0xa1, 0x55, 0x5c, 0x29, 0x2c,
	0xa3, 0x55, 0x29, 0xb5, 0xf4, 0x0f, 0xec, 0xd2, 0xe8, 0x1e, 0x93, 0x05, 0xe5, 0xc2, 0x49, 0x7f,
	0xe8, 0xa3, 0xd1, 0x15, 0x61, 0x55, 0xca, 0x8f, 0x3c, 0xc7, 0xdd, 0x1a, 0xbd, 0x28, 0x50, 0xe8,
	0x5a, 0x3b, 0x6e, 0x34, 0xa5, 0xa9, 0xae, 0x94, 0x5b, 0x0d, 0x2f, 0x09, 0xf4, 0xa6, 0x7c, 0x21,
	0x90, 0xcd, 0x56, 0xbe, 0x0f, 0x5e, 0x55, 0x71, 0x16, 0x90, 0x31, 0x39, 0xe9, 0x27, 0x36, 0xf6,
	0x9f, 0xc3, 0x2d, 0x0b, 0x34, 0x77, 0xb6, 0xe0, 0xc6, 0x98, 0x9c, 0x0c, 0x9e, 0xdc, 0x8d, 0x5c,
	0xb5, 0xe8, 0xad, 0xd1, 0xa6, 0x56, 0x4a, 0x06, 0xf8, 0xfb, 0xc1, 0x8f, 0xa0, 0x5b, 0xb3, 0x05,
	0x1d, 0x6b, 0x39, 0x6e, 0x2c, 0x76, 0x96, 0x89, 0xd3, 0x92, 0x26, 0xc9, 0x7f, 0x00, 0x9e, 0x11,
	0x02, 0xcf, 0x26, 0x1f, 0x5d, 0x49, 0x9e, 0x29, 0x2c, 0x13, 0x2b, 0x87, 0x9f, 0x1a, 0xdc, 0x77,
	0xa2, 0x55, 0xdc, 0xa6, 0x7d, 0x67, 0x7f, 0xfb, 0xcf, 0xd0, 0x77, 0xed, 0xdf, 0x57, 0xfa, 0x3a,
	0xfa, 0x7f, 0x21, 0x30, 0x7c, 0x95, 0xa6, 0xb2, 0x12, 0xfa, 0x0c, 0x73, 0xd4, 0xc8, 0xae, 0x83,
	0xe2, 0x27, 0x81, 0x61, 0xfd, 0x02, 0x67, 0x2b, 0x46, 0xdb, 0xa6, 0x78, 0x06, 0x03, 0x99, 0xb3,
	0xf9, 0xbf, 0x1c, 0x1f, 0x90, 0x39, 0xab, 0x63, 0x63, 0x13, 0xb8, 0xd9, 0xda, 0xbc, 0x7d, 0x36,
	0x81, 0x9b, 0x3a, 0x0e, 0x7f, 0x10, 0xb8, 0x33, 0xa1, 0x4a, 0x6d, 0x64, 0xc9, 0xde, 0x64, 0x54,
	0x2c, 0x5a, 0x9e, 0xe6, 0x11, 0xf4, 0xcc, 0x34, 0xfb, 0xf7, 0xb5, 0x2b, 0x73, 0x66, 0x02, 0x93,
	0x6d, 0x86, 0xd8, 0xff, 0x29, 0x74, 0x05, 0x6e, 0x4c, 0x10, 0x7e, 0x27, 0x70, 0xdb, 0x04, 0x6a,
	0x8a, 0xb4, 0x4c, 0xb3, 0x96, 0xc9, 0x0f, 0xa1, 0xb3, 0xc4, 0x0b, 0x0b, 0xdd, 0x4f, 0x4c, 0xe8,
	0x3f, 0x84, 0x03, 0x43, 0xa1, 0x02, 0x6f, 0xdc, 0xd9, 0x8d, 0xe6, 0xf4, 0xf0, 0x2b, 0x81, 0xa1,
	0x05, 0x4b, 0x50, 0x97, 0x1c, 0xd7, 0x2d, 0x93, 0x6d, 0x39, 0x3a, 0x7f, 0xe1, 0xb8, 0x24, 0x70,
	0xd8, 0xbc, 0xf4, 0xff, 0x42, 0x72, 0x1f, 0xfa, 0xa6, 0xd3, 0xdc, 0x16, 0x74, 0x3b, 0xd5, 0x33,
	0x0b, 0x33, 0x53, 0xf4, 0x31, 0xf4, 0xea, 0xd3, 0xd8, 0xec, 0xd8, 0xee, 0xe3, 0xb8, 0xcd, 0x0a,
	0xbf, 0x11, 0x18, 0x4c, 0xdc, 0x6f, 0xfb, 0x4c, 0x0a, 0x6c, 0xfd, 0x8f, 0xec, 0x4a, 0xef, 0xfe,
	0xa4, 0x9c, 0x96, 0x34, 0x49, 0xaf, 0x5f, 0x7e, 0x78, 0xb1, 0xe0, 0x3a, 0xab, 0xce, 0xa3, 0x54,
	0x16, 0x31, 0xcf, 0x33, 0x5a, 0x14, 0x19, 0x63, 0xf1, 0xb2, 0x62, 0x74, 0xc9, 0x4f, 0x8d, 0xe9,
	0x54, 0x61, 0xb9, 0xe6, 0x29, 0xc6, 0x28, 0x34, 0xd7, 0x1c, 0x55, 0xec, 0xee, 0xb3, 0xf3, 0x9b,
	0xf6, 0x76, 0x79, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x44, 0x50, 0x74, 0x0d, 0xe0, 0x06, 0x00,
	0x00,
}
